#r "../../../packages/Suave.Git/lib/Suave.Git.dll" 
#r "../../../packages/Newtonsoft.Json/lib/portable-net40+sl5+wp80+win8+wpa81/Newtonsoft.Json.dll" 
#r "../../../packages/System.ValueTuple/lib/portable-net40+sl4+win8+wp8/System.ValueTuple.dll" 
#r "../../../packages/Mono.Cecil/lib/sl5/Mono.Cecil.dll" 
#r "../../../packages/Mono.Cecil/lib/sl5/Mono.Cecil.Rocks.dll" 