((nil . ((eval . (set
                  (make-local-variable 'inferior-fsharp-program)
                  (let* ((d (dir-locals-find-file "."))
                         (basedir (if (stringp d) (file-name-directory d) (car d)))
                         (shell-nix (concat basedir "/src/Scripts/Nix/shell.nix"))
                         (nix-cmd  (concat "nix-shell " shell-nix " -A irisEnv"))
                         (main (concat "--use:" basedir "/.paket/load/net461/main.group.fsx"))
                         (iris (concat "--use:" basedir "/src/Scripts/Fsx/Iris.Core.fsx"))
                         (fsi  (concat "fsi --readline- " main " " iris))
                         (run  (concat "--run \"" fsi "\"")))
                    (concat nix-cmd " " run)))))))
