#load @"System.Collections.fsx" 
#load @"System.Globalization.fsx" 
#load @"System.Resources.ResourceManager.fsx" 
#load @"System.Runtime.fsx" 
#load @"System.Runtime.Extensions.fsx" 
#load @"System.Runtime.Handles.fsx" 
#load @"System.Runtime.InteropServices.fsx" 
#r "../../../packages/Microsoft.Win32.Registry/lib/net46/Microsoft.Win32.Registry.dll" 