#load @"System.Reflection.fsx" 
#load @"System.Reflection.Primitives.fsx" 
#load @"System.Runtime.fsx" 
#load @"System.Runtime.Handles.fsx" 
#r "../../../packages/System.Runtime.InteropServices/lib/net462/System.Runtime.InteropServices.dll" 