// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Serialization")]
[assembly: AssemblyProductAttribute("Iris")]
[assembly: AssemblyDescriptionAttribute("VVVV Automation Infrastructure")]
[assembly: AssemblyVersionAttribute("0.3.1")]
[assembly: AssemblyFileVersionAttribute("0.3.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.3.1";
        internal const string InformationalVersion = "0.3.1";
    }
}
