#load @"system.collections.fsx" 
#load @"system.globalization.fsx" 
#load @"system.resources.resourcemanager.fsx" 
#load @"system.runtime.fsx" 
#load @"system.runtime.extensions.fsx" 
#load @"system.runtime.handles.fsx" 
#load @"system.runtime.interopservices.fsx" 
#r "../../packages/Microsoft.Win32.Registry/lib/net46/Microsoft.Win32.Registry.dll" 