#load @"system.diagnostics.debug.fsx" 
#load @"system.diagnostics.tracing.fsx" 
#load @"system.resources.resourcemanager.fsx" 
#load @"system.runtime.fsx" 
#load @"system.threading.fsx" 
#r "../../packages/System.Buffers/lib/netstandard1.1/System.Buffers.dll" 