#load @"system.io.fsx" 
#load @"system.net.primitives.fsx" 
#load @"system.runtime.fsx" 
#load @"system.threading.tasks.fsx" 
#r "System" 
#r "../../packages/System.Net.Sockets/lib/net46/System.Net.Sockets.dll" 