// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class AlreadyVotedFB : Table {
  public static AlreadyVotedFB GetRootAsAlreadyVotedFB(ByteBuffer _bb) { return GetRootAsAlreadyVotedFB(_bb, new AlreadyVotedFB()); }
  public static AlreadyVotedFB GetRootAsAlreadyVotedFB(ByteBuffer _bb, AlreadyVotedFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AlreadyVotedFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartAlreadyVotedFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<AlreadyVotedFB> EndAlreadyVotedFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AlreadyVotedFB>(o);
  }
};


}
