// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class AppendEntryFailedFB : Table {
  public static AppendEntryFailedFB GetRootAsAppendEntryFailedFB(ByteBuffer _bb) { return GetRootAsAppendEntryFailedFB(_bb, new AppendEntryFailedFB()); }
  public static AppendEntryFailedFB GetRootAsAppendEntryFailedFB(ByteBuffer _bb, AppendEntryFailedFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AppendEntryFailedFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartAppendEntryFailedFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<AppendEntryFailedFB> EndAppendEntryFailedFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AppendEntryFailedFB>(o);
  }
};


}
