// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class CandidateUnknownFB : Table {
  public static CandidateUnknownFB GetRootAsCandidateUnknownFB(ByteBuffer _bb) { return GetRootAsCandidateUnknownFB(_bb, new CandidateUnknownFB()); }
  public static CandidateUnknownFB GetRootAsCandidateUnknownFB(ByteBuffer _bb, CandidateUnknownFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public CandidateUnknownFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartCandidateUnknownFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<CandidateUnknownFB> EndCandidateUnknownFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CandidateUnknownFB>(o);
  }
};


}
