// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class EntryInvalidatedFB : Table {
  public static EntryInvalidatedFB GetRootAsEntryInvalidatedFB(ByteBuffer _bb) { return GetRootAsEntryInvalidatedFB(_bb, new EntryInvalidatedFB()); }
  public static EntryInvalidatedFB GetRootAsEntryInvalidatedFB(ByteBuffer _bb, EntryInvalidatedFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public EntryInvalidatedFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartEntryInvalidatedFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<EntryInvalidatedFB> EndEntryInvalidatedFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EntryInvalidatedFB>(o);
  }
};


}
