// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class InvalidCurrentIndexFB : Table {
  public static InvalidCurrentIndexFB GetRootAsInvalidCurrentIndexFB(ByteBuffer _bb) { return GetRootAsInvalidCurrentIndexFB(_bb, new InvalidCurrentIndexFB()); }
  public static InvalidCurrentIndexFB GetRootAsInvalidCurrentIndexFB(ByteBuffer _bb, InvalidCurrentIndexFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public InvalidCurrentIndexFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartInvalidCurrentIndexFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<InvalidCurrentIndexFB> EndInvalidCurrentIndexFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<InvalidCurrentIndexFB>(o);
  }
};


}
