// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class InvalidLastLogTermFB : Table {
  public static InvalidLastLogTermFB GetRootAsInvalidLastLogTermFB(ByteBuffer _bb) { return GetRootAsInvalidLastLogTermFB(_bb, new InvalidLastLogTermFB()); }
  public static InvalidLastLogTermFB GetRootAsInvalidLastLogTermFB(ByteBuffer _bb, InvalidLastLogTermFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public InvalidLastLogTermFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartInvalidLastLogTermFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<InvalidLastLogTermFB> EndInvalidLastLogTermFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<InvalidLastLogTermFB>(o);
  }
};


}
