// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class InvalidLastLogFB : Table {
  public static InvalidLastLogFB GetRootAsInvalidLastLogFB(ByteBuffer _bb) { return GetRootAsInvalidLastLogFB(_bb, new InvalidLastLogFB()); }
  public static InvalidLastLogFB GetRootAsInvalidLastLogFB(ByteBuffer _bb, InvalidLastLogFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public InvalidLastLogFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartInvalidLastLogFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<InvalidLastLogFB> EndInvalidLastLogFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<InvalidLastLogFB>(o);
  }
};


}
