// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class InvalidTermFB : Table {
  public static InvalidTermFB GetRootAsInvalidTermFB(ByteBuffer _bb) { return GetRootAsInvalidTermFB(_bb, new InvalidTermFB()); }
  public static InvalidTermFB GetRootAsInvalidTermFB(ByteBuffer _bb, InvalidTermFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public InvalidTermFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartInvalidTermFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<InvalidTermFB> EndInvalidTermFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<InvalidTermFB>(o);
  }
};


}
