// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class LogIncompleteFB : Table {
  public static LogIncompleteFB GetRootAsLogIncompleteFB(ByteBuffer _bb) { return GetRootAsLogIncompleteFB(_bb, new LogIncompleteFB()); }
  public static LogIncompleteFB GetRootAsLogIncompleteFB(ByteBuffer _bb, LogIncompleteFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public LogIncompleteFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartLogIncompleteFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<LogIncompleteFB> EndLogIncompleteFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LogIncompleteFB>(o);
  }
};


}
