// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class NoErrorFB : Table {
  public static NoErrorFB GetRootAsNoErrorFB(ByteBuffer _bb) { return GetRootAsNoErrorFB(_bb, new NoErrorFB()); }
  public static NoErrorFB GetRootAsNoErrorFB(ByteBuffer _bb, NoErrorFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public NoErrorFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartNoErrorFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<NoErrorFB> EndNoErrorFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NoErrorFB>(o);
  }
};


}
