// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class NotCandidateFB : Table {
  public static NotCandidateFB GetRootAsNotCandidateFB(ByteBuffer _bb) { return GetRootAsNotCandidateFB(_bb, new NotCandidateFB()); }
  public static NotCandidateFB GetRootAsNotCandidateFB(ByteBuffer _bb, NotCandidateFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public NotCandidateFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartNotCandidateFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<NotCandidateFB> EndNotCandidateFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NotCandidateFB>(o);
  }
};


}
