// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class NotLeaderFB : Table {
  public static NotLeaderFB GetRootAsNotLeaderFB(ByteBuffer _bb) { return GetRootAsNotLeaderFB(_bb, new NotLeaderFB()); }
  public static NotLeaderFB GetRootAsNotLeaderFB(ByteBuffer _bb, NotLeaderFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public NotLeaderFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartNotLeaderFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<NotLeaderFB> EndNotLeaderFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NotLeaderFB>(o);
  }
};


}
