// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class NotVotingStateFB : Table {
  public static NotVotingStateFB GetRootAsNotVotingStateFB(ByteBuffer _bb) { return GetRootAsNotVotingStateFB(_bb, new NotVotingStateFB()); }
  public static NotVotingStateFB GetRootAsNotVotingStateFB(ByteBuffer _bb, NotVotingStateFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public NotVotingStateFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartNotVotingStateFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<NotVotingStateFB> EndNotVotingStateFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NotVotingStateFB>(o);
  }
};


}
