// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class OtherErrorFB : Table {
  public static OtherErrorFB GetRootAsOtherErrorFB(ByteBuffer _bb) { return GetRootAsOtherErrorFB(_bb, new OtherErrorFB()); }
  public static OtherErrorFB GetRootAsOtherErrorFB(ByteBuffer _bb, OtherErrorFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public OtherErrorFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string Message { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetMessageBytes() { return __vector_as_arraysegment(4); }

  public static Offset<OtherErrorFB> CreateOtherErrorFB(FlatBufferBuilder builder,
      StringOffset MessageOffset = default(StringOffset)) {
    builder.StartObject(1);
    OtherErrorFB.AddMessage(builder, MessageOffset);
    return OtherErrorFB.EndOtherErrorFB(builder);
  }

  public static void StartOtherErrorFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset MessageOffset) { builder.AddOffset(0, MessageOffset.Value, 0); }
  public static Offset<OtherErrorFB> EndOtherErrorFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<OtherErrorFB>(o);
  }
};


}
