// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

public enum RaftErrorFB : byte
{
 NONE = 0,
 AlreadyVotedFB = 1,
 AppendEntryFailedFB = 2,
 CandidateUnknownFB = 3,
 EntryInvalidatedFB = 4,
 InvalidCurrentIndexFB = 5,
 InvalidLastLogFB = 6,
 InvalidLastLogTermFB = 7,
 InvalidTermFB = 8,
 LogFormatErrorFB = 9,
 LogIncompleteFB = 10,
 NoErrorFB = 11,
 NoNodeFB = 12,
 NotCandidateFB = 13,
 NotLeaderFB = 14,
 NotVotingStateFB = 15,
 ResponseTimeoutFB = 16,
 SnapshotFormatErrorFB = 17,
 StaleResponseFB = 18,
 UnexpectedVotingChangeFB = 19,
 VoteTermMismatchFB = 20,
 OtherErrorFB = 21,
};


}
