// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class RemoveClient : Table {
  public static RemoveClient GetRootAsRemoveClient(ByteBuffer _bb) { return GetRootAsRemoveClient(_bb, new RemoveClient()); }
  public static RemoveClient GetRootAsRemoveClient(ByteBuffer _bb, RemoveClient obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public RemoveClient __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Iris.Serialization.Client Payload { get { return GetPayload(new Iris.Serialization.Client()); } }
  public Iris.Serialization.Client GetPayload(Iris.Serialization.Client obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<RemoveClient> CreateRemoveClient(FlatBufferBuilder builder,
      Offset<Iris.Serialization.Client> PayloadOffset = default(Offset<Iris.Serialization.Client>)) {
    builder.StartObject(1);
    RemoveClient.AddPayload(builder, PayloadOffset);
    return RemoveClient.EndRemoveClient(builder);
  }

  public static void StartRemoveClient(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<Iris.Serialization.Client> PayloadOffset) { builder.AddOffset(0, PayloadOffset.Value, 0); }
  public static Offset<RemoveClient> EndRemoveClient(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveClient>(o);
  }
};


}
