// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class ResponseTimeoutFB : Table {
  public static ResponseTimeoutFB GetRootAsResponseTimeoutFB(ByteBuffer _bb) { return GetRootAsResponseTimeoutFB(_bb, new ResponseTimeoutFB()); }
  public static ResponseTimeoutFB GetRootAsResponseTimeoutFB(ByteBuffer _bb, ResponseTimeoutFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public ResponseTimeoutFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartResponseTimeoutFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<ResponseTimeoutFB> EndResponseTimeoutFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ResponseTimeoutFB>(o);
  }
};


}
