// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

public enum SliceType : byte
{
 NONE = 0,
 ByteSlice = 1,
 UByteSlice = 2,
 BoolSlice = 3,
 ShortSlice = 4,
 UShortSlice = 5,
 IntSlice = 6,
 UIntSlice = 7,
 FloatSlice = 8,
 LongSlice = 9,
 ULongSlice = 10,
 DoubleSlice = 11,
 StringSlice = 12,
};


}
