// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class SnapshotFormatErrorFB : Table {
  public static SnapshotFormatErrorFB GetRootAsSnapshotFormatErrorFB(ByteBuffer _bb) { return GetRootAsSnapshotFormatErrorFB(_bb, new SnapshotFormatErrorFB()); }
  public static SnapshotFormatErrorFB GetRootAsSnapshotFormatErrorFB(ByteBuffer _bb, SnapshotFormatErrorFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public SnapshotFormatErrorFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartSnapshotFormatErrorFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<SnapshotFormatErrorFB> EndSnapshotFormatErrorFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SnapshotFormatErrorFB>(o);
  }
};


}
