// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class StaleResponseFB : Table {
  public static StaleResponseFB GetRootAsStaleResponseFB(ByteBuffer _bb) { return GetRootAsStaleResponseFB(_bb, new StaleResponseFB()); }
  public static StaleResponseFB GetRootAsStaleResponseFB(ByteBuffer _bb, StaleResponseFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public StaleResponseFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartStaleResponseFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<StaleResponseFB> EndStaleResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<StaleResponseFB>(o);
  }
};


}
