// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class StopClient : Table {
  public static StopClient GetRootAsStopClient(ByteBuffer _bb) { return GetRootAsStopClient(_bb, new StopClient()); }
  public static StopClient GetRootAsStopClient(ByteBuffer _bb, StopClient obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public StopClient __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Iris.Serialization.Client Payload { get { return GetPayload(new Iris.Serialization.Client()); } }
  public Iris.Serialization.Client GetPayload(Iris.Serialization.Client obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<StopClient> CreateStopClient(FlatBufferBuilder builder,
      Offset<Iris.Serialization.Client> PayloadOffset = default(Offset<Iris.Serialization.Client>)) {
    builder.StartObject(1);
    StopClient.AddPayload(builder, PayloadOffset);
    return StopClient.EndStopClient(builder);
  }

  public static void StartStopClient(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<Iris.Serialization.Client> PayloadOffset) { builder.AddOffset(0, PayloadOffset.Value, 0); }
  public static Offset<StopClient> EndStopClient(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<StopClient>(o);
  }
};


}
