// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

public enum StringType : short
{
 Simple = 0,
 MultiLine = 1,
 FileName = 2,
 Directory = 3,
 Url = 4,
 IP = 5,
};


}
