// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class ULongSlice : Table {
  public static ULongSlice GetRootAsULongSlice(ByteBuffer _bb) { return GetRootAsULongSlice(_bb, new ULongSlice()); }
  public static ULongSlice GetRootAsULongSlice(ByteBuffer _bb, ULongSlice obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public ULongSlice __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte Index { get { int o = __offset(4); return o != 0 ? bb.Get(o + bb_pos) : (byte)0; } }
  public ulong Value { get { int o = __offset(6); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }

  public static Offset<ULongSlice> CreateULongSlice(FlatBufferBuilder builder,
      byte Index = 0,
      ulong Value = 0) {
    builder.StartObject(2);
    ULongSlice.AddValue(builder, Value);
    ULongSlice.AddIndex(builder, Index);
    return ULongSlice.EndULongSlice(builder);
  }

  public static void StartULongSlice(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIndex(FlatBufferBuilder builder, byte Index) { builder.AddByte(0, Index, 0); }
  public static void AddValue(FlatBufferBuilder builder, ulong Value) { builder.AddUlong(1, Value, 0); }
  public static Offset<ULongSlice> EndULongSlice(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ULongSlice>(o);
  }
};


}
