// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class VoteTermMismatchFB : Table {
  public static VoteTermMismatchFB GetRootAsVoteTermMismatchFB(ByteBuffer _bb) { return GetRootAsVoteTermMismatchFB(_bb, new VoteTermMismatchFB()); }
  public static VoteTermMismatchFB GetRootAsVoteTermMismatchFB(ByteBuffer _bb, VoteTermMismatchFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public VoteTermMismatchFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartVoteTermMismatchFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<VoteTermMismatchFB> EndVoteTermMismatchFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<VoteTermMismatchFB>(o);
  }
};


}
