// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization
{

using System;
using FlatBuffers;

public sealed class VoteResponseFB : Table {
  public static VoteResponseFB GetRootAsVoteResponseFB(ByteBuffer _bb) { return GetRootAsVoteResponseFB(_bb, new VoteResponseFB()); }
  public static VoteResponseFB GetRootAsVoteResponseFB(ByteBuffer _bb, VoteResponseFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public VoteResponseFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ulong Term { get { int o = __offset(4); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public bool Granted { get { int o = __offset(6); return o != 0 ? 0!=bb.Get(o + bb_pos) : (bool)false; } }
  public RaftErrorFB ReasonType { get { int o = __offset(8); return o != 0 ? (RaftErrorFB)bb.Get(o + bb_pos) : RaftErrorFB.NONE; } }
  public TTable GetReason<TTable>(TTable obj) where TTable : Table { int o = __offset(10); return o != 0 ? __union(obj, o) : null; }

  public static Offset<VoteResponseFB> CreateVoteResponseFB(FlatBufferBuilder builder,
      ulong Term = 0,
      bool Granted = false,
      RaftErrorFB Reason_type = RaftErrorFB.NONE,
      int ReasonOffset = 0) {
    builder.StartObject(4);
    VoteResponseFB.AddTerm(builder, Term);
    VoteResponseFB.AddReason(builder, ReasonOffset);
    VoteResponseFB.AddReasonType(builder, Reason_type);
    VoteResponseFB.AddGranted(builder, Granted);
    return VoteResponseFB.EndVoteResponseFB(builder);
  }

  public static void StartVoteResponseFB(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddTerm(FlatBufferBuilder builder, ulong Term) { builder.AddUlong(0, Term, 0); }
  public static void AddGranted(FlatBufferBuilder builder, bool Granted) { builder.AddBool(1, Granted, false); }
  public static void AddReasonType(FlatBufferBuilder builder, RaftErrorFB ReasonType) { builder.AddByte(2, (byte)ReasonType, 0); }
  public static void AddReason(FlatBufferBuilder builder, int ReasonOffset) { builder.AddOffset(3, ReasonOffset, 0); }
  public static Offset<VoteResponseFB> EndVoteResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<VoteResponseFB>(o);
  }
};


}
