// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Types
{

using System;
using FlatBuffers;

public sealed class AddClient : Table {
  public static AddClient GetRootAsAddClient(ByteBuffer _bb) { return GetRootAsAddClient(_bb, new AddClient()); }
  public static AddClient GetRootAsAddClient(ByteBuffer _bb, AddClient obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AddClient __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Iris.Types.Client Payload { get { return GetPayload(new Iris.Types.Client()); } }
  public Iris.Types.Client GetPayload(Iris.Types.Client obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<AddClient> CreateAddClient(FlatBufferBuilder builder,
      Offset<Iris.Types.Client> PayloadOffset = default(Offset<Iris.Types.Client>)) {
    builder.StartObject(1);
    AddClient.AddPayload(builder, PayloadOffset);
    return AddClient.EndAddClient(builder);
  }

  public static void StartAddClient(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<Iris.Types.Client> PayloadOffset) { builder.AddOffset(0, PayloadOffset.Value, 0); }
  public static Offset<AddClient> EndAddClient(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddClient>(o);
  }
};


}
