// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Types
{

using System;
using FlatBuffers;

public sealed class Cue : Table {
  public static Cue GetRootAsCue(ByteBuffer _bb) { return GetRootAsCue(_bb, new Cue()); }
  public static Cue GetRootAsCue(ByteBuffer _bb, Cue obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public Cue __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string Id { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIdBytes() { return __vector_as_arraysegment(4); }
  public string Name { get { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __vector_as_arraysegment(6); }

  public static Offset<Cue> CreateCue(FlatBufferBuilder builder,
      StringOffset IdOffset = default(StringOffset),
      StringOffset NameOffset = default(StringOffset)) {
    builder.StartObject(2);
    Cue.AddName(builder, NameOffset);
    Cue.AddId(builder, IdOffset);
    return Cue.EndCue(builder);
  }

  public static void StartCue(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddId(FlatBufferBuilder builder, StringOffset IdOffset) { builder.AddOffset(0, IdOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(1, NameOffset.Value, 0); }
  public static Offset<Cue> EndCue(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Cue>(o);
  }
  public static void FinishCueBuffer(FlatBufferBuilder builder, Offset<Cue> offset) { builder.Finish(offset.Value); }
};


}
