// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Types
{

using System;
using FlatBuffers;

public sealed class DoubleSlice : Table {
  public static DoubleSlice GetRootAsDoubleSlice(ByteBuffer _bb) { return GetRootAsDoubleSlice(_bb, new DoubleSlice()); }
  public static DoubleSlice GetRootAsDoubleSlice(ByteBuffer _bb, DoubleSlice obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public DoubleSlice __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte Index { get { int o = __offset(4); return o != 0 ? bb.Get(o + bb_pos) : (byte)0; } }
  public double Value { get { int o = __offset(6); return o != 0 ? bb.GetDouble(o + bb_pos) : (double)0.0; } }

  public static Offset<DoubleSlice> CreateDoubleSlice(FlatBufferBuilder builder,
      byte Index = 0,
      double Value = 0.0) {
    builder.StartObject(2);
    DoubleSlice.AddValue(builder, Value);
    DoubleSlice.AddIndex(builder, Index);
    return DoubleSlice.EndDoubleSlice(builder);
  }

  public static void StartDoubleSlice(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIndex(FlatBufferBuilder builder, byte Index) { builder.AddByte(0, Index, 0); }
  public static void AddValue(FlatBufferBuilder builder, double Value) { builder.AddDouble(1, Value, 0.0); }
  public static Offset<DoubleSlice> EndDoubleSlice(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DoubleSlice>(o);
  }
};


}
