// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Types
{

using System;
using FlatBuffers;

public sealed class FloatSlice : Table {
  public static FloatSlice GetRootAsFloatSlice(ByteBuffer _bb) { return GetRootAsFloatSlice(_bb, new FloatSlice()); }
  public static FloatSlice GetRootAsFloatSlice(ByteBuffer _bb, FloatSlice obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public FloatSlice __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte Index { get { int o = __offset(4); return o != 0 ? bb.Get(o + bb_pos) : (byte)0; } }
  public float Value { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }

  public static Offset<FloatSlice> CreateFloatSlice(FlatBufferBuilder builder,
      byte Index = 0,
      float Value = 0.0f) {
    builder.StartObject(2);
    FloatSlice.AddValue(builder, Value);
    FloatSlice.AddIndex(builder, Index);
    return FloatSlice.EndFloatSlice(builder);
  }

  public static void StartFloatSlice(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIndex(FlatBufferBuilder builder, byte Index) { builder.AddByte(0, Index, 0); }
  public static void AddValue(FlatBufferBuilder builder, float Value) { builder.AddFloat(1, Value, 0.0f); }
  public static Offset<FloatSlice> EndFloatSlice(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FloatSlice>(o);
  }
};


}
