// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Types
{

using System;
using FlatBuffers;

public sealed class LoadSnapshot : Table {
  public static LoadSnapshot GetRootAsLoadSnapshot(ByteBuffer _bb) { return GetRootAsLoadSnapshot(_bb, new LoadSnapshot()); }
  public static LoadSnapshot GetRootAsLoadSnapshot(ByteBuffer _bb, LoadSnapshot obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public LoadSnapshot __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Iris.Types.Snapshot Payload { get { return GetPayload(new Iris.Types.Snapshot()); } }
  public Iris.Types.Snapshot GetPayload(Iris.Types.Snapshot obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<LoadSnapshot> CreateLoadSnapshot(FlatBufferBuilder builder,
      Offset<Iris.Types.Snapshot> PayloadOffset = default(Offset<Iris.Types.Snapshot>)) {
    builder.StartObject(1);
    LoadSnapshot.AddPayload(builder, PayloadOffset);
    return LoadSnapshot.EndLoadSnapshot(builder);
  }

  public static void StartLoadSnapshot(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<Iris.Types.Snapshot> PayloadOffset) { builder.AddOffset(0, PayloadOffset.Value, 0); }
  public static Offset<LoadSnapshot> EndLoadSnapshot(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoadSnapshot>(o);
  }
};


}
