// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Types
{

public enum ReplicatedCommand : byte
{
 NONE = 0,
 AddCue = 1,
 UpdateCue = 2,
 RemoveCue = 3,
 AddClient = 4,
 StartClient = 5,
 StopClient = 6,
 UpdateClient = 7,
 RemoveClient = 8,
 LoadSnapshot = 9,
};


}
