// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Types
{

using System;
using FlatBuffers;

public sealed class StartClient : Table {
  public static StartClient GetRootAsStartClient(ByteBuffer _bb) { return GetRootAsStartClient(_bb, new StartClient()); }
  public static StartClient GetRootAsStartClient(ByteBuffer _bb, StartClient obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public StartClient __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Iris.Types.Client Payload { get { return GetPayload(new Iris.Types.Client()); } }
  public Iris.Types.Client GetPayload(Iris.Types.Client obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<StartClient> CreateStartClient(FlatBufferBuilder builder,
      Offset<Iris.Types.Client> PayloadOffset = default(Offset<Iris.Types.Client>)) {
    builder.StartObject(1);
    StartClient.AddPayload(builder, PayloadOffset);
    return StartClient.EndStartClient(builder);
  }

  public static void StartStartClient(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<Iris.Types.Client> PayloadOffset) { builder.AddOffset(0, PayloadOffset.Value, 0); }
  public static Offset<StartClient> EndStartClient(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<StartClient>(o);
  }
};


}
