// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Types
{

using System;
using FlatBuffers;

public sealed class UpdateClient : Table {
  public static UpdateClient GetRootAsUpdateClient(ByteBuffer _bb) { return GetRootAsUpdateClient(_bb, new UpdateClient()); }
  public static UpdateClient GetRootAsUpdateClient(ByteBuffer _bb, UpdateClient obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public UpdateClient __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Iris.Types.Client Payload { get { return GetPayload(new Iris.Types.Client()); } }
  public Iris.Types.Client GetPayload(Iris.Types.Client obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<UpdateClient> CreateUpdateClient(FlatBufferBuilder builder,
      Offset<Iris.Types.Client> PayloadOffset = default(Offset<Iris.Types.Client>)) {
    builder.StartObject(1);
    UpdateClient.AddPayload(builder, PayloadOffset);
    return UpdateClient.EndUpdateClient(builder);
  }

  public static void StartUpdateClient(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<Iris.Types.Client> PayloadOffset) { builder.AddOffset(0, PayloadOffset.Value, 0); }
  public static Offset<UpdateClient> EndUpdateClient(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdateClient>(o);
  }
};


}
