// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum ActionTypeFB : ushort
{
 AddFB = 0,
 UpdateFB = 1,
 RemoveFB = 2,
 LogMsgFB = 3,
 AppCommandFB = 4,
 DataSnapshotFB = 5,
};


}
