// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum ActionTypeFB : ushort
{
 AddFB = 0,
 UpdateFB = 1,
 RemoveFB = 2,
 LogMsgFB = 3,
 DataSnapshotFB = 4,
 UndoFB = 5,
 RedoFB = 6,
 ResetFB = 7,
 SaveProjectFB = 8,
};


}
