// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class AddCueFB : Table {
  public static AddCueFB GetRootAsAddCueFB(ByteBuffer _bb) { return GetRootAsAddCueFB(_bb, new AddCueFB()); }
  public static AddCueFB GetRootAsAddCueFB(ByteBuffer _bb, AddCueFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AddCueFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public CueFB Cue { get { return GetCue(new CueFB()); } }
  public CueFB GetCue(CueFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<AddCueFB> CreateAddCueFB(FlatBufferBuilder builder,
      Offset<CueFB> CueOffset = default(Offset<CueFB>)) {
    builder.StartObject(1);
    AddCueFB.AddCue(builder, CueOffset);
    return AddCueFB.EndAddCueFB(builder);
  }

  public static void StartAddCueFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCue(FlatBufferBuilder builder, Offset<CueFB> CueOffset) { builder.AddOffset(0, CueOffset.Value, 0); }
  public static Offset<AddCueFB> EndAddCueFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddCueFB>(o);
  }
};


}
