// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct AddCueFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddCueFB GetRootAsAddCueFB(ByteBuffer _bb) { return GetRootAsAddCueFB(_bb, new AddCueFB()); }
  public static AddCueFB GetRootAsAddCueFB(ByteBuffer _bb, AddCueFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddCueFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CueFB? Cue { get { int o = __p.__offset(4); return o != 0 ? (CueFB?)(new CueFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<AddCueFB> CreateAddCueFB(FlatBufferBuilder builder,
      Offset<CueFB> CueOffset = default(Offset<CueFB>)) {
    builder.StartObject(1);
    AddCueFB.AddCue(builder, CueOffset);
    return AddCueFB.EndAddCueFB(builder);
  }

  public static void StartAddCueFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCue(FlatBufferBuilder builder, Offset<CueFB> CueOffset) { builder.AddOffset(0, CueOffset.Value, 0); }
  public static Offset<AddCueFB> EndAddCueFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddCueFB>(o);
  }
};


}
