// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct AddIOBoxFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddIOBoxFB GetRootAsAddIOBoxFB(ByteBuffer _bb) { return GetRootAsAddIOBoxFB(_bb, new AddIOBoxFB()); }
  public static AddIOBoxFB GetRootAsAddIOBoxFB(ByteBuffer _bb, AddIOBoxFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddIOBoxFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public IOBoxFB? IOBox { get { int o = __p.__offset(4); return o != 0 ? (IOBoxFB?)(new IOBoxFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<AddIOBoxFB> CreateAddIOBoxFB(FlatBufferBuilder builder,
      Offset<IOBoxFB> IOBoxOffset = default(Offset<IOBoxFB>)) {
    builder.StartObject(1);
    AddIOBoxFB.AddIOBox(builder, IOBoxOffset);
    return AddIOBoxFB.EndAddIOBoxFB(builder);
  }

  public static void StartAddIOBoxFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddIOBox(FlatBufferBuilder builder, Offset<IOBoxFB> IOBoxOffset) { builder.AddOffset(0, IOBoxOffset.Value, 0); }
  public static Offset<AddIOBoxFB> EndAddIOBoxFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddIOBoxFB>(o);
  }
};


}
