// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class AddSessionFB : Table {
  public static AddSessionFB GetRootAsAddSessionFB(ByteBuffer _bb) { return GetRootAsAddSessionFB(_bb, new AddSessionFB()); }
  public static AddSessionFB GetRootAsAddSessionFB(ByteBuffer _bb, AddSessionFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AddSessionFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public SessionFB Session { get { return GetSession(new SessionFB()); } }
  public SessionFB GetSession(SessionFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<AddSessionFB> CreateAddSessionFB(FlatBufferBuilder builder,
      Offset<SessionFB> SessionOffset = default(Offset<SessionFB>)) {
    builder.StartObject(1);
    AddSessionFB.AddSession(builder, SessionOffset);
    return AddSessionFB.EndAddSessionFB(builder);
  }

  public static void StartAddSessionFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSession(FlatBufferBuilder builder, Offset<SessionFB> SessionOffset) { builder.AddOffset(0, SessionOffset.Value, 0); }
  public static Offset<AddSessionFB> EndAddSessionFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddSessionFB>(o);
  }
};


}
