// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class AddUserFB : Table {
  public static AddUserFB GetRootAsAddUserFB(ByteBuffer _bb) { return GetRootAsAddUserFB(_bb, new AddUserFB()); }
  public static AddUserFB GetRootAsAddUserFB(ByteBuffer _bb, AddUserFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AddUserFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public UserFB User { get { return GetUser(new UserFB()); } }
  public UserFB GetUser(UserFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<AddUserFB> CreateAddUserFB(FlatBufferBuilder builder,
      Offset<UserFB> UserOffset = default(Offset<UserFB>)) {
    builder.StartObject(1);
    AddUserFB.AddUser(builder, UserOffset);
    return AddUserFB.EndAddUserFB(builder);
  }

  public static void StartAddUserFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUser(FlatBufferBuilder builder, Offset<UserFB> UserOffset) { builder.AddOffset(0, UserOffset.Value, 0); }
  public static Offset<AddUserFB> EndAddUserFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddUserFB>(o);
  }
};


}
