// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class AppCommandFB : Table {
  public static AppCommandFB GetRootAsAppCommandFB(ByteBuffer _bb) { return GetRootAsAppCommandFB(_bb, new AppCommandFB()); }
  public static AppCommandFB GetRootAsAppCommandFB(ByteBuffer _bb, AppCommandFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AppCommandFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public AppCommandTypeFB Command { get { int o = __offset(4); return o != 0 ? (AppCommandTypeFB)bb.GetUshort(o + bb_pos) : AppCommandTypeFB.UndoFB; } }

  public static Offset<AppCommandFB> CreateAppCommandFB(FlatBufferBuilder builder,
      AppCommandTypeFB Command = AppCommandTypeFB.UndoFB) {
    builder.StartObject(1);
    AppCommandFB.AddCommand(builder, Command);
    return AppCommandFB.EndAppCommandFB(builder);
  }

  public static void StartAppCommandFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCommand(FlatBufferBuilder builder, AppCommandTypeFB Command) { builder.AddUshort(0, (ushort)Command, 0); }
  public static Offset<AppCommandFB> EndAppCommandFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AppCommandFB>(o);
  }
};


}
