// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class AppendResponseFB : Table {
  public static AppendResponseFB GetRootAsAppendResponseFB(ByteBuffer _bb) { return GetRootAsAppendResponseFB(_bb, new AppendResponseFB()); }
  public static AppendResponseFB GetRootAsAppendResponseFB(ByteBuffer _bb, AppendResponseFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public AppendResponseFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ulong Term { get { int o = __offset(4); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public bool Success { get { int o = __offset(6); return o != 0 ? 0!=bb.Get(o + bb_pos) : (bool)false; } }
  public ulong CurrentIndex { get { int o = __offset(8); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public ulong FirstIndex { get { int o = __offset(10); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }

  public static Offset<AppendResponseFB> CreateAppendResponseFB(FlatBufferBuilder builder,
      ulong Term = 0,
      bool Success = false,
      ulong CurrentIndex = 0,
      ulong FirstIndex = 0) {
    builder.StartObject(4);
    AppendResponseFB.AddFirstIndex(builder, FirstIndex);
    AppendResponseFB.AddCurrentIndex(builder, CurrentIndex);
    AppendResponseFB.AddTerm(builder, Term);
    AppendResponseFB.AddSuccess(builder, Success);
    return AppendResponseFB.EndAppendResponseFB(builder);
  }

  public static void StartAppendResponseFB(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddTerm(FlatBufferBuilder builder, ulong Term) { builder.AddUlong(0, Term, 0); }
  public static void AddSuccess(FlatBufferBuilder builder, bool Success) { builder.AddBool(1, Success, false); }
  public static void AddCurrentIndex(FlatBufferBuilder builder, ulong CurrentIndex) { builder.AddUlong(2, CurrentIndex, 0); }
  public static void AddFirstIndex(FlatBufferBuilder builder, ulong FirstIndex) { builder.AddUlong(3, FirstIndex, 0); }
  public static Offset<AppendResponseFB> EndAppendResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AppendResponseFB>(o);
  }
};


}
