// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class ApplicationEventFB : Table {
  public static ApplicationEventFB GetRootAsApplicationEventFB(ByteBuffer _bb) { return GetRootAsApplicationEventFB(_bb, new ApplicationEventFB()); }
  public static ApplicationEventFB GetRootAsApplicationEventFB(ByteBuffer _bb, ApplicationEventFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public ApplicationEventFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ApplicationEventTypeFB AppEventType { get { int o = __offset(4); return o != 0 ? (ApplicationEventTypeFB)bb.Get(o + bb_pos) : ApplicationEventTypeFB.NONE; } }
  public TTable GetAppEvent<TTable>(TTable obj) where TTable : Table { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static Offset<ApplicationEventFB> CreateApplicationEventFB(FlatBufferBuilder builder,
      ApplicationEventTypeFB AppEvent_type = ApplicationEventTypeFB.NONE,
      int AppEventOffset = 0) {
    builder.StartObject(2);
    ApplicationEventFB.AddAppEvent(builder, AppEventOffset);
    ApplicationEventFB.AddAppEventType(builder, AppEvent_type);
    return ApplicationEventFB.EndApplicationEventFB(builder);
  }

  public static void StartApplicationEventFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAppEventType(FlatBufferBuilder builder, ApplicationEventTypeFB AppEventType) { builder.AddByte(0, (byte)AppEventType, 0); }
  public static void AddAppEvent(FlatBufferBuilder builder, int AppEventOffset) { builder.AddOffset(1, AppEventOffset, 0); }
  public static Offset<ApplicationEventFB> EndApplicationEventFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ApplicationEventFB>(o);
  }
};


}
