// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct ArrivederciFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ArrivederciFB GetRootAsArrivederciFB(ByteBuffer _bb) { return GetRootAsArrivederciFB(_bb, new ArrivederciFB()); }
  public static ArrivederciFB GetRootAsArrivederciFB(ByteBuffer _bb, ArrivederciFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ArrivederciFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartArrivederciFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<ArrivederciFB> EndArrivederciFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ArrivederciFB>(o);
  }
};


}
