// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct BoolBoxFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BoolBoxFB GetRootAsBoolBoxFB(ByteBuffer _bb) { return GetRootAsBoolBoxFB(_bb, new BoolBoxFB()); }
  public static BoolBoxFB GetRootAsBoolBoxFB(ByteBuffer _bb, BoolBoxFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BoolBoxFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public string Patch { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPatchBytes() { return __p.__vector_as_arraysegment(8); }
  public string Tags(int j) { int o = __p.__offset(10); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int TagsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public BehaviorFB Behavior { get { int o = __p.__offset(12); return o != 0 ? (BehaviorFB)__p.bb.GetUshort(o + __p.bb_pos) : BehaviorFB.ToggleFB; } }
  public BoolSliceFB? Slices(int j) { int o = __p.__offset(14); return o != 0 ? (BoolSliceFB?)(new BoolSliceFB()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SlicesLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<BoolBoxFB> CreateBoolBoxFB(FlatBufferBuilder builder,
      StringOffset IdOffset = default(StringOffset),
      StringOffset NameOffset = default(StringOffset),
      StringOffset PatchOffset = default(StringOffset),
      VectorOffset TagsOffset = default(VectorOffset),
      BehaviorFB Behavior = BehaviorFB.ToggleFB,
      VectorOffset SlicesOffset = default(VectorOffset)) {
    builder.StartObject(6);
    BoolBoxFB.AddSlices(builder, SlicesOffset);
    BoolBoxFB.AddTags(builder, TagsOffset);
    BoolBoxFB.AddPatch(builder, PatchOffset);
    BoolBoxFB.AddName(builder, NameOffset);
    BoolBoxFB.AddId(builder, IdOffset);
    BoolBoxFB.AddBehavior(builder, Behavior);
    return BoolBoxFB.EndBoolBoxFB(builder);
  }

  public static void StartBoolBoxFB(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddId(FlatBufferBuilder builder, StringOffset IdOffset) { builder.AddOffset(0, IdOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(1, NameOffset.Value, 0); }
  public static void AddPatch(FlatBufferBuilder builder, StringOffset PatchOffset) { builder.AddOffset(2, PatchOffset.Value, 0); }
  public static void AddTags(FlatBufferBuilder builder, VectorOffset TagsOffset) { builder.AddOffset(3, TagsOffset.Value, 0); }
  public static VectorOffset CreateTagsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartTagsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBehavior(FlatBufferBuilder builder, BehaviorFB Behavior) { builder.AddUshort(4, (ushort)Behavior, 0); }
  public static void AddSlices(FlatBufferBuilder builder, VectorOffset SlicesOffset) { builder.AddOffset(5, SlicesOffset.Value, 0); }
  public static VectorOffset CreateSlicesVector(FlatBufferBuilder builder, Offset<BoolSliceFB>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartSlicesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BoolBoxFB> EndBoolBoxFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BoolBoxFB>(o);
  }
};


}
