// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct BoolSliceFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BoolSliceFB GetRootAsBoolSliceFB(ByteBuffer _bb) { return GetRootAsBoolSliceFB(_bb, new BoolSliceFB()); }
  public static BoolSliceFB GetRootAsBoolSliceFB(ByteBuffer _bb, BoolSliceFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BoolSliceFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Index { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool Value { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<BoolSliceFB> CreateBoolSliceFB(FlatBufferBuilder builder,
      uint Index = 0,
      bool Value = false) {
    builder.StartObject(2);
    BoolSliceFB.AddIndex(builder, Index);
    BoolSliceFB.AddValue(builder, Value);
    return BoolSliceFB.EndBoolSliceFB(builder);
  }

  public static void StartBoolSliceFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIndex(FlatBufferBuilder builder, uint Index) { builder.AddUint(0, Index, 0); }
  public static void AddValue(FlatBufferBuilder builder, bool Value) { builder.AddBool(1, Value, false); }
  public static Offset<BoolSliceFB> EndBoolSliceFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BoolSliceFB>(o);
  }
};


}
