// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct ByteSliceFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ByteSliceFB GetRootAsByteSliceFB(ByteBuffer _bb) { return GetRootAsByteSliceFB(_bb, new ByteSliceFB()); }
  public static ByteSliceFB GetRootAsByteSliceFB(ByteBuffer _bb, ByteSliceFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ByteSliceFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Index { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Value { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetValueBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<ByteSliceFB> CreateByteSliceFB(FlatBufferBuilder builder,
      uint Index = 0,
      StringOffset ValueOffset = default(StringOffset)) {
    builder.StartObject(2);
    ByteSliceFB.AddValue(builder, ValueOffset);
    ByteSliceFB.AddIndex(builder, Index);
    return ByteSliceFB.EndByteSliceFB(builder);
  }

  public static void StartByteSliceFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIndex(FlatBufferBuilder builder, uint Index) { builder.AddUint(0, Index, 0); }
  public static void AddValue(FlatBufferBuilder builder, StringOffset ValueOffset) { builder.AddOffset(1, ValueOffset.Value, 0); }
  public static Offset<ByteSliceFB> EndByteSliceFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ByteSliceFB>(o);
  }
};


}
