// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum ColorSpaceTypeFB : byte
{
 NONE = 0,
 RGBAValueFB = 1,
 HSLAValueFB = 2,
};


}
