// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class ColorSliceFB : Table {
  public static ColorSliceFB GetRootAsColorSliceFB(ByteBuffer _bb) { return GetRootAsColorSliceFB(_bb, new ColorSliceFB()); }
  public static ColorSliceFB GetRootAsColorSliceFB(ByteBuffer _bb, ColorSliceFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public ColorSliceFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ulong Index { get { int o = __offset(4); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public ColorSpaceFB Value { get { return GetValue(new ColorSpaceFB()); } }
  public ColorSpaceFB GetValue(ColorSpaceFB obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<ColorSliceFB> CreateColorSliceFB(FlatBufferBuilder builder,
      ulong Index = 0,
      Offset<ColorSpaceFB> ValueOffset = default(Offset<ColorSpaceFB>)) {
    builder.StartObject(2);
    ColorSliceFB.AddIndex(builder, Index);
    ColorSliceFB.AddValue(builder, ValueOffset);
    return ColorSliceFB.EndColorSliceFB(builder);
  }

  public static void StartColorSliceFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIndex(FlatBufferBuilder builder, ulong Index) { builder.AddUlong(0, Index, 0); }
  public static void AddValue(FlatBufferBuilder builder, Offset<ColorSpaceFB> ValueOffset) { builder.AddOffset(1, ValueOffset.Value, 0); }
  public static Offset<ColorSliceFB> EndColorSliceFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ColorSliceFB>(o);
  }
};


}
