// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class CompoundSliceFB : Table {
  public static CompoundSliceFB GetRootAsCompoundSliceFB(ByteBuffer _bb) { return GetRootAsCompoundSliceFB(_bb, new CompoundSliceFB()); }
  public static CompoundSliceFB GetRootAsCompoundSliceFB(ByteBuffer _bb, CompoundSliceFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public CompoundSliceFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ulong Index { get { int o = __offset(4); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public string GetValue(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int ValueLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<CompoundSliceFB> CreateCompoundSliceFB(FlatBufferBuilder builder,
      ulong Index = 0,
      VectorOffset ValueOffset = default(VectorOffset)) {
    builder.StartObject(2);
    CompoundSliceFB.AddIndex(builder, Index);
    CompoundSliceFB.AddValue(builder, ValueOffset);
    return CompoundSliceFB.EndCompoundSliceFB(builder);
  }

  public static void StartCompoundSliceFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIndex(FlatBufferBuilder builder, ulong Index) { builder.AddUlong(0, Index, 0); }
  public static void AddValue(FlatBufferBuilder builder, VectorOffset ValueOffset) { builder.AddOffset(1, ValueOffset.Value, 0); }
  public static VectorOffset CreateValueVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartValueVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CompoundSliceFB> EndCompoundSliceFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CompoundSliceFB>(o);
  }
};


}
