// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct DataSnapshotFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DataSnapshotFB GetRootAsDataSnapshotFB(ByteBuffer _bb) { return GetRootAsDataSnapshotFB(_bb, new DataSnapshotFB()); }
  public static DataSnapshotFB GetRootAsDataSnapshotFB(ByteBuffer _bb, DataSnapshotFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DataSnapshotFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public StateFB? Data { get { int o = __p.__offset(4); return o != 0 ? (StateFB?)(new StateFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<DataSnapshotFB> CreateDataSnapshotFB(FlatBufferBuilder builder,
      Offset<StateFB> DataOffset = default(Offset<StateFB>)) {
    builder.StartObject(1);
    DataSnapshotFB.AddData(builder, DataOffset);
    return DataSnapshotFB.EndDataSnapshotFB(builder);
  }

  public static void StartDataSnapshotFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddData(FlatBufferBuilder builder, Offset<StateFB> DataOffset) { builder.AddOffset(0, DataOffset.Value, 0); }
  public static Offset<DataSnapshotFB> EndDataSnapshotFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DataSnapshotFB>(o);
  }
};


}
