// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class EmptyResponseFB : Table {
  public static EmptyResponseFB GetRootAsEmptyResponseFB(ByteBuffer _bb) { return GetRootAsEmptyResponseFB(_bb, new EmptyResponseFB()); }
  public static EmptyResponseFB GetRootAsEmptyResponseFB(ByteBuffer _bb, EmptyResponseFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public EmptyResponseFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartEmptyResponseFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<EmptyResponseFB> EndEmptyResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EmptyResponseFB>(o);
  }
};


}
