// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct EmptyResponseFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static EmptyResponseFB GetRootAsEmptyResponseFB(ByteBuffer _bb) { return GetRootAsEmptyResponseFB(_bb, new EmptyResponseFB()); }
  public static EmptyResponseFB GetRootAsEmptyResponseFB(ByteBuffer _bb, EmptyResponseFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EmptyResponseFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartEmptyResponseFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<EmptyResponseFB> EndEmptyResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EmptyResponseFB>(o);
  }
};


}
