// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct EnumPropertyFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static EnumPropertyFB GetRootAsEnumPropertyFB(ByteBuffer _bb) { return GetRootAsEnumPropertyFB(_bb, new EnumPropertyFB()); }
  public static EnumPropertyFB GetRootAsEnumPropertyFB(ByteBuffer _bb, EnumPropertyFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EnumPropertyFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Key { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(4); }
  public string Value { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetValueBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<EnumPropertyFB> CreateEnumPropertyFB(FlatBufferBuilder builder,
      StringOffset KeyOffset = default(StringOffset),
      StringOffset ValueOffset = default(StringOffset)) {
    builder.StartObject(2);
    EnumPropertyFB.AddValue(builder, ValueOffset);
    EnumPropertyFB.AddKey(builder, KeyOffset);
    return EnumPropertyFB.EndEnumPropertyFB(builder);
  }

  public static void StartEnumPropertyFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddKey(FlatBufferBuilder builder, StringOffset KeyOffset) { builder.AddOffset(0, KeyOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, StringOffset ValueOffset) { builder.AddOffset(1, ValueOffset.Value, 0); }
  public static Offset<EnumPropertyFB> EndEnumPropertyFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EnumPropertyFB>(o);
  }
};


}
