// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct ErrorFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ErrorFB GetRootAsErrorFB(ByteBuffer _bb) { return GetRootAsErrorFB(_bb, new ErrorFB()); }
  public static ErrorFB GetRootAsErrorFB(ByteBuffer _bb, ErrorFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ErrorFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorTypeFB Type { get { int o = __p.__offset(4); return o != 0 ? (ErrorTypeFB)__p.bb.GetUshort(o + __p.bb_pos) : ErrorTypeFB.BranchNotFoundFB; } }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<ErrorFB> CreateErrorFB(FlatBufferBuilder builder,
      ErrorTypeFB Type = ErrorTypeFB.BranchNotFoundFB,
      StringOffset MessageOffset = default(StringOffset)) {
    builder.StartObject(2);
    ErrorFB.AddMessage(builder, MessageOffset);
    ErrorFB.AddType(builder, Type);
    return ErrorFB.EndErrorFB(builder);
  }

  public static void StartErrorFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddType(FlatBufferBuilder builder, ErrorTypeFB Type) { builder.AddUshort(0, (ushort)Type, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset MessageOffset) { builder.AddOffset(1, MessageOffset.Value, 0); }
  public static Offset<ErrorFB> EndErrorFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ErrorFB>(o);
  }
};


}
