// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum ErrorTypeFB : ushort
{
 BranchNotFoundFB = 0,
 BranchDetailsNotFoundFB = 1,
 RepositoryNotFoundFB = 2,
 RepositoryInitFailedFB = 3,
 CommitErrorFB = 4,
 GitErrorFB = 5,
 ProjectNotFoundFB = 6,
 ProjectParseErrorFB = 7,
 ProjectPathErrorFB = 8,
 ProjectSaveErrorFB = 9,
 ProjectInitErrorFB = 10,
 MetaDataNotFoundFB = 11,
 MissingStartupDirFB = 12,
 CliParseErrorFB = 13,
 MissingNodeIdFB = 14,
 MissingNodeFB = 15,
 AssetNotFoundErrorFB = 16,
 AssetLoadErrorFB = 17,
 AssetSaveErrorFB = 18,
 AssetDeleteErrorFB = 19,
 ParseErrorFB = 20,
 SocketErrorFB = 21,
 OKFB = 22,
 AlreadyVotedFB = 23,
 AppendEntryFailedFB = 24,
 CandidateUnknownFB = 25,
 EntryInvalidatedFB = 26,
 InvalidCurrentIndexFB = 27,
 InvalidLastLogFB = 28,
 InvalidLastLogTermFB = 29,
 InvalidTermFB = 30,
 LogFormatErrorFB = 31,
 LogIncompleteFB = 32,
 NoErrorFB = 33,
 NoNodeFB = 34,
 NotCandidateFB = 35,
 NotLeaderFB = 36,
 NotVotingStateFB = 37,
 ResponseTimeoutFB = 38,
 SnapshotFormatErrorFB = 39,
 StaleResponseFB = 40,
 UnexpectedVotingChangeFB = 41,
 VoteTermMismatchFB = 42,
 OtherFB = 43,
};


}
