// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum ErrorTypeFB : ushort
{
 BranchNotFoundFB = 0,
 BranchDetailsNotFoundFB = 1,
 RepositoryNotFoundFB = 2,
 RepositoryInitFailedFB = 3,
 CommitErrorFB = 4,
 GitErrorFB = 5,
 ProjectNotFoundFB = 6,
 ProjectParseErrorFB = 7,
 ProjectPathErrorFB = 8,
 ProjectSaveErrorFB = 9,
 ProjectInitErrorFB = 10,
 MetaDataNotFoundFB = 11,
 MissingStartupDirFB = 12,
 CliParseErrorFB = 13,
 MissingNodeIdFB = 14,
 MissingNodeFB = 15,
 AssetNotFoundErrorFB = 16,
 AssetLoadErrorFB = 17,
 AssetSaveErrorFB = 18,
 AssetDeleteErrorFB = 19,
 ParseErrorFB = 20,
 SocketErrorFB = 21,
 IOErrorFB = 22,
 OKFB = 23,
 AlreadyVotedFB = 24,
 AppendEntryFailedFB = 25,
 CandidateUnknownFB = 26,
 EntryInvalidatedFB = 27,
 InvalidCurrentIndexFB = 28,
 InvalidLastLogFB = 29,
 InvalidLastLogTermFB = 30,
 InvalidTermFB = 31,
 LogFormatErrorFB = 32,
 LogIncompleteFB = 33,
 NoErrorFB = 34,
 NoNodeFB = 35,
 NotCandidateFB = 36,
 NotLeaderFB = 37,
 NotVotingStateFB = 38,
 ResponseTimeoutFB = 39,
 SnapshotFormatErrorFB = 40,
 StaleResponseFB = 41,
 UnexpectedVotingChangeFB = 42,
 VoteTermMismatchFB = 43,
 OtherFB = 44,
};


}
