// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class ErrorResponseFB : Table {
  public static ErrorResponseFB GetRootAsErrorResponseFB(ByteBuffer _bb) { return GetRootAsErrorResponseFB(_bb, new ErrorResponseFB()); }
  public static ErrorResponseFB GetRootAsErrorResponseFB(ByteBuffer _bb, ErrorResponseFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public ErrorResponseFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public RaftErrorFB Error { get { return GetError(new RaftErrorFB()); } }
  public RaftErrorFB GetError(RaftErrorFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<ErrorResponseFB> CreateErrorResponseFB(FlatBufferBuilder builder,
      Offset<RaftErrorFB> ErrorOffset = default(Offset<RaftErrorFB>)) {
    builder.StartObject(1);
    ErrorResponseFB.AddError(builder, ErrorOffset);
    return ErrorResponseFB.EndErrorResponseFB(builder);
  }

  public static void StartErrorResponseFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddError(FlatBufferBuilder builder, Offset<RaftErrorFB> ErrorOffset) { builder.AddOffset(0, ErrorOffset.Value, 0); }
  public static Offset<ErrorResponseFB> EndErrorResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ErrorResponseFB>(o);
  }
};


}
