// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum ErrorTypeFB : ushort
{
 BranchNotFoundFB = 0,
 BranchDetailsNotFoundFB = 1,
 RepositoryNotFoundFB = 2,
 RepositoryInitFailedFB = 3,
 CommitErrorFB = 4,
 GitErrorFB = 5,
 ProjectNotFoundFB = 6,
 ProjectParseErrorFB = 7,
 ProjectPathErrorFB = 8,
 ProjectSaveErrorFB = 9,
 ProjectInitErrorFB = 10,
 MetaDataNotFoundFB = 11,
 MissingStartupDirFB = 12,
 CliParseErrorFB = 13,
 MissingNodeIdFB = 14,
 MissingNodeFB = 15,
 AssetSaveErrorFB = 16,
 AssetDeleteErrorFB = 17,
 OKFB = 18,
 AlreadyVotedFB = 19,
 AppendEntryFailedFB = 20,
 CandidateUnknownFB = 21,
 EntryInvalidatedFB = 22,
 InvalidCurrentIndexFB = 23,
 InvalidLastLogFB = 24,
 InvalidLastLogTermFB = 25,
 InvalidTermFB = 26,
 LogFormatErrorFB = 27,
 LogIncompleteFB = 28,
 NoErrorFB = 29,
 NoNodeFB = 30,
 NotCandidateFB = 31,
 NotLeaderFB = 32,
 NotVotingStateFB = 33,
 ResponseTimeoutFB = 34,
 SnapshotFormatErrorFB = 35,
 StaleResponseFB = 36,
 UnexpectedVotingChangeFB = 37,
 VoteTermMismatchFB = 38,
 OtherFB = 39,
};


}
