// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class IntSliceFB : Table {
  public static IntSliceFB GetRootAsIntSliceFB(ByteBuffer _bb) { return GetRootAsIntSliceFB(_bb, new IntSliceFB()); }
  public static IntSliceFB GetRootAsIntSliceFB(ByteBuffer _bb, IntSliceFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public IntSliceFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ulong Index { get { int o = __offset(4); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public int Value { get { int o = __offset(6); return o != 0 ? bb.GetInt(o + bb_pos) : (int)0; } }

  public static Offset<IntSliceFB> CreateIntSliceFB(FlatBufferBuilder builder,
      ulong Index = 0,
      int Value = 0) {
    builder.StartObject(2);
    IntSliceFB.AddIndex(builder, Index);
    IntSliceFB.AddValue(builder, Value);
    return IntSliceFB.EndIntSliceFB(builder);
  }

  public static void StartIntSliceFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIndex(FlatBufferBuilder builder, ulong Index) { builder.AddUlong(0, Index, 0); }
  public static void AddValue(FlatBufferBuilder builder, int Value) { builder.AddInt(1, Value, 0); }
  public static Offset<IntSliceFB> EndIntSliceFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<IntSliceFB>(o);
  }
};


}
