// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class IOBoxFB : Table {
  public static IOBoxFB GetRootAsIOBoxFB(ByteBuffer _bb) { return GetRootAsIOBoxFB(_bb, new IOBoxFB()); }
  public static IOBoxFB GetRootAsIOBoxFB(ByteBuffer _bb, IOBoxFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public IOBoxFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string Id { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetIdBytes() { return __vector_as_arraysegment(4); }
  public string Name { get { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __vector_as_arraysegment(6); }

  public static Offset<IOBoxFB> CreateIOBoxFB(FlatBufferBuilder builder,
      StringOffset IdOffset = default(StringOffset),
      StringOffset NameOffset = default(StringOffset)) {
    builder.StartObject(2);
    IOBoxFB.AddName(builder, NameOffset);
    IOBoxFB.AddId(builder, IdOffset);
    return IOBoxFB.EndIOBoxFB(builder);
  }

  public static void StartIOBoxFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddId(FlatBufferBuilder builder, StringOffset IdOffset) { builder.AddOffset(0, IdOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(1, NameOffset.Value, 0); }
  public static Offset<IOBoxFB> EndIOBoxFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<IOBoxFB>(o);
  }
};


}
