// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class IOBoxFB : Table {
  public static IOBoxFB GetRootAsIOBoxFB(ByteBuffer _bb) { return GetRootAsIOBoxFB(_bb, new IOBoxFB()); }
  public static IOBoxFB GetRootAsIOBoxFB(ByteBuffer _bb, IOBoxFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public IOBoxFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public IOBoxTypeFB IOBoxType { get { int o = __offset(4); return o != 0 ? (IOBoxTypeFB)bb.Get(o + bb_pos) : IOBoxTypeFB.NONE; } }
  public TTable GetIOBox<TTable>(TTable obj) where TTable : Table { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static Offset<IOBoxFB> CreateIOBoxFB(FlatBufferBuilder builder,
      IOBoxTypeFB IOBox_type = IOBoxTypeFB.NONE,
      int IOBoxOffset = 0) {
    builder.StartObject(2);
    IOBoxFB.AddIOBox(builder, IOBoxOffset);
    IOBoxFB.AddIOBoxType(builder, IOBox_type);
    return IOBoxFB.EndIOBoxFB(builder);
  }

  public static void StartIOBoxFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddIOBoxType(FlatBufferBuilder builder, IOBoxTypeFB IOBoxType) { builder.AddByte(0, (byte)IOBoxType, 0); }
  public static void AddIOBox(FlatBufferBuilder builder, int IOBoxOffset) { builder.AddOffset(1, IOBoxOffset, 0); }
  public static Offset<IOBoxFB> EndIOBoxFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<IOBoxFB>(o);
  }
};


}
