// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum IOBoxTypeFB : byte
{
 NONE = 0,
 StringBoxFB = 1,
 IntBoxFB = 2,
 FloatBoxFB = 3,
 DoubleBoxFB = 4,
 BoolBoxFB = 5,
 ByteBoxFB = 6,
 EnumBoxFB = 7,
 ColorBoxFB = 8,
 CompoundBoxFB = 9,
};


}
