// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class LogFB : Table {
  public static LogFB GetRootAsLogFB(ByteBuffer _bb) { return GetRootAsLogFB(_bb, new LogFB()); }
  public static LogFB GetRootAsLogFB(ByteBuffer _bb, LogFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public LogFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public LogTypeFB EntryType { get { int o = __offset(4); return o != 0 ? (LogTypeFB)bb.Get(o + bb_pos) : LogTypeFB.NONE; } }
  public TTable GetEntry<TTable>(TTable obj) where TTable : Table { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static Offset<LogFB> CreateLogFB(FlatBufferBuilder builder,
      LogTypeFB Entry_type = LogTypeFB.NONE,
      int EntryOffset = 0) {
    builder.StartObject(2);
    LogFB.AddEntry(builder, EntryOffset);
    LogFB.AddEntryType(builder, Entry_type);
    return LogFB.EndLogFB(builder);
  }

  public static void StartLogFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddEntryType(FlatBufferBuilder builder, LogTypeFB EntryType) { builder.AddByte(0, (byte)EntryType, 0); }
  public static void AddEntry(FlatBufferBuilder builder, int EntryOffset) { builder.AddOffset(1, EntryOffset, 0); }
  public static Offset<LogFB> EndLogFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LogFB>(o);
  }
};


}
