// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum LogTypeFB : byte
{
 NONE = 0,
 ConfigChangeFB = 1,
 JointConsensusFB = 2,
 EntryFB = 3,
 SnapshotFB = 4,
};


}
