// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum PayloadFB : byte
{
 NONE = 0,
 CueFB = 1,
 CueListFB = 2,
 IOBoxFB = 3,
 PatchFB = 4,
 NodeFB = 5,
 UserFB = 6,
 SessionFB = 7,
 LogMsgFB = 8,
 StateFB = 9,
};


}
