// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RaftErrorFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RaftErrorFB GetRootAsRaftErrorFB(ByteBuffer _bb) { return GetRootAsRaftErrorFB(_bb, new RaftErrorFB()); }
  public static RaftErrorFB GetRootAsRaftErrorFB(ByteBuffer _bb, RaftErrorFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RaftErrorFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public RaftErrorTypeFB Type { get { int o = __p.__offset(4); return o != 0 ? (RaftErrorTypeFB)__p.bb.GetUshort(o + __p.bb_pos) : RaftErrorTypeFB.AlreadyVotedFB; } }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<RaftErrorFB> CreateRaftErrorFB(FlatBufferBuilder builder,
      RaftErrorTypeFB Type = RaftErrorTypeFB.AlreadyVotedFB,
      StringOffset MessageOffset = default(StringOffset)) {
    builder.StartObject(2);
    RaftErrorFB.AddMessage(builder, MessageOffset);
    RaftErrorFB.AddType(builder, Type);
    return RaftErrorFB.EndRaftErrorFB(builder);
  }

  public static void StartRaftErrorFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddType(FlatBufferBuilder builder, RaftErrorTypeFB Type) { builder.AddUshort(0, (ushort)Type, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset MessageOffset) { builder.AddOffset(1, MessageOffset.Value, 0); }
  public static Offset<RaftErrorFB> EndRaftErrorFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RaftErrorFB>(o);
  }
};


}
