// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum RaftErrorTypeFB : ushort
{
 AlreadyVotedFB = 0,
 AppendEntryFailedFB = 1,
 CandidateUnknownFB = 2,
 EntryInvalidatedFB = 3,
 InvalidCurrentIndexFB = 4,
 InvalidLastLogFB = 5,
 InvalidLastLogTermFB = 6,
 InvalidTermFB = 7,
 LogFormatErrorFB = 8,
 LogIncompleteFB = 9,
 NoErrorFB = 10,
 NoNodeFB = 11,
 NotCandidateFB = 12,
 NotLeaderFB = 13,
 NotVotingStateFB = 14,
 ResponseTimeoutFB = 15,
 SnapshotFormatErrorFB = 16,
 StaleResponseFB = 17,
 UnexpectedVotingChangeFB = 18,
 VoteTermMismatchFB = 19,
 OtherErrorFB = 20,
};


}
