// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum RaftMsgTypeFB : byte
{
 NONE = 0,
 RequestVoteFB = 1,
 RequestVoteResponseFB = 2,
 RequestAppendEntriesFB = 3,
 RequestAppendResponseFB = 4,
 RequestInstallSnapshotFB = 5,
 RequestSnapshotResponseFB = 6,
 HandShakeFB = 7,
 HandWaiveFB = 8,
 RedirectFB = 9,
 WelcomeFB = 10,
 ArrivederciFB = 11,
 ErrorResponseFB = 12,
 EmptyResponseFB = 13,
};


}
