// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class RedirectFB : Table {
  public static RedirectFB GetRootAsRedirectFB(ByteBuffer _bb) { return GetRootAsRedirectFB(_bb, new RedirectFB()); }
  public static RedirectFB GetRootAsRedirectFB(ByteBuffer _bb, RedirectFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public RedirectFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public NodeFB Node { get { return GetNode(new NodeFB()); } }
  public NodeFB GetNode(NodeFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<RedirectFB> CreateRedirectFB(FlatBufferBuilder builder,
      Offset<NodeFB> NodeOffset = default(Offset<NodeFB>)) {
    builder.StartObject(1);
    RedirectFB.AddNode(builder, NodeOffset);
    return RedirectFB.EndRedirectFB(builder);
  }

  public static void StartRedirectFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddNode(FlatBufferBuilder builder, Offset<NodeFB> NodeOffset) { builder.AddOffset(0, NodeOffset.Value, 0); }
  public static Offset<RedirectFB> EndRedirectFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RedirectFB>(o);
  }
};


}
