// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class RemoveNodeFB : Table {
  public static RemoveNodeFB GetRootAsRemoveNodeFB(ByteBuffer _bb) { return GetRootAsRemoveNodeFB(_bb, new RemoveNodeFB()); }
  public static RemoveNodeFB GetRootAsRemoveNodeFB(ByteBuffer _bb, RemoveNodeFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public RemoveNodeFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public NodeFB Node { get { return GetNode(new NodeFB()); } }
  public NodeFB GetNode(NodeFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<RemoveNodeFB> CreateRemoveNodeFB(FlatBufferBuilder builder,
      Offset<NodeFB> NodeOffset = default(Offset<NodeFB>)) {
    builder.StartObject(1);
    RemoveNodeFB.AddNode(builder, NodeOffset);
    return RemoveNodeFB.EndRemoveNodeFB(builder);
  }

  public static void StartRemoveNodeFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddNode(FlatBufferBuilder builder, Offset<NodeFB> NodeOffset) { builder.AddOffset(0, NodeOffset.Value, 0); }
  public static Offset<RemoveNodeFB> EndRemoveNodeFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveNodeFB>(o);
  }
};


}
