// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RemoveIOBoxFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoveIOBoxFB GetRootAsRemoveIOBoxFB(ByteBuffer _bb) { return GetRootAsRemoveIOBoxFB(_bb, new RemoveIOBoxFB()); }
  public static RemoveIOBoxFB GetRootAsRemoveIOBoxFB(ByteBuffer _bb, RemoveIOBoxFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoveIOBoxFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public IOBoxFB? IOBox { get { int o = __p.__offset(4); return o != 0 ? (IOBoxFB?)(new IOBoxFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RemoveIOBoxFB> CreateRemoveIOBoxFB(FlatBufferBuilder builder,
      Offset<IOBoxFB> IOBoxOffset = default(Offset<IOBoxFB>)) {
    builder.StartObject(1);
    RemoveIOBoxFB.AddIOBox(builder, IOBoxOffset);
    return RemoveIOBoxFB.EndRemoveIOBoxFB(builder);
  }

  public static void StartRemoveIOBoxFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddIOBox(FlatBufferBuilder builder, Offset<IOBoxFB> IOBoxOffset) { builder.AddOffset(0, IOBoxOffset.Value, 0); }
  public static Offset<RemoveIOBoxFB> EndRemoveIOBoxFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveIOBoxFB>(o);
  }
};


}
