// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RemoveCueFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoveCueFB GetRootAsRemoveCueFB(ByteBuffer _bb) { return GetRootAsRemoveCueFB(_bb, new RemoveCueFB()); }
  public static RemoveCueFB GetRootAsRemoveCueFB(ByteBuffer _bb, RemoveCueFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoveCueFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CueFB? Cue { get { int o = __p.__offset(4); return o != 0 ? (CueFB?)(new CueFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RemoveCueFB> CreateRemoveCueFB(FlatBufferBuilder builder,
      Offset<CueFB> CueOffset = default(Offset<CueFB>)) {
    builder.StartObject(1);
    RemoveCueFB.AddCue(builder, CueOffset);
    return RemoveCueFB.EndRemoveCueFB(builder);
  }

  public static void StartRemoveCueFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCue(FlatBufferBuilder builder, Offset<CueFB> CueOffset) { builder.AddOffset(0, CueOffset.Value, 0); }
  public static Offset<RemoveCueFB> EndRemoveCueFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveCueFB>(o);
  }
};


}
