// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class RemoveCueFB : Table {
  public static RemoveCueFB GetRootAsRemoveCueFB(ByteBuffer _bb) { return GetRootAsRemoveCueFB(_bb, new RemoveCueFB()); }
  public static RemoveCueFB GetRootAsRemoveCueFB(ByteBuffer _bb, RemoveCueFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public RemoveCueFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public CueFB Cue { get { return GetCue(new CueFB()); } }
  public CueFB GetCue(CueFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<RemoveCueFB> CreateRemoveCueFB(FlatBufferBuilder builder,
      Offset<CueFB> CueOffset = default(Offset<CueFB>)) {
    builder.StartObject(1);
    RemoveCueFB.AddCue(builder, CueOffset);
    return RemoveCueFB.EndRemoveCueFB(builder);
  }

  public static void StartRemoveCueFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCue(FlatBufferBuilder builder, Offset<CueFB> CueOffset) { builder.AddOffset(0, CueOffset.Value, 0); }
  public static Offset<RemoveCueFB> EndRemoveCueFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveCueFB>(o);
  }
};


}
