// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class RemoveUserFB : Table {
  public static RemoveUserFB GetRootAsRemoveUserFB(ByteBuffer _bb) { return GetRootAsRemoveUserFB(_bb, new RemoveUserFB()); }
  public static RemoveUserFB GetRootAsRemoveUserFB(ByteBuffer _bb, RemoveUserFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public RemoveUserFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public UserFB User { get { return GetUser(new UserFB()); } }
  public UserFB GetUser(UserFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<RemoveUserFB> CreateRemoveUserFB(FlatBufferBuilder builder,
      Offset<UserFB> UserOffset = default(Offset<UserFB>)) {
    builder.StartObject(1);
    RemoveUserFB.AddUser(builder, UserOffset);
    return RemoveUserFB.EndRemoveUserFB(builder);
  }

  public static void StartRemoveUserFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUser(FlatBufferBuilder builder, Offset<UserFB> UserOffset) { builder.AddOffset(0, UserOffset.Value, 0); }
  public static Offset<RemoveUserFB> EndRemoveUserFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveUserFB>(o);
  }
};


}
