// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RemovePatchFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemovePatchFB GetRootAsRemovePatchFB(ByteBuffer _bb) { return GetRootAsRemovePatchFB(_bb, new RemovePatchFB()); }
  public static RemovePatchFB GetRootAsRemovePatchFB(ByteBuffer _bb, RemovePatchFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemovePatchFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PatchFB? Patch { get { int o = __p.__offset(4); return o != 0 ? (PatchFB?)(new PatchFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RemovePatchFB> CreateRemovePatchFB(FlatBufferBuilder builder,
      Offset<PatchFB> PatchOffset = default(Offset<PatchFB>)) {
    builder.StartObject(1);
    RemovePatchFB.AddPatch(builder, PatchOffset);
    return RemovePatchFB.EndRemovePatchFB(builder);
  }

  public static void StartRemovePatchFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPatch(FlatBufferBuilder builder, Offset<PatchFB> PatchOffset) { builder.AddOffset(0, PatchOffset.Value, 0); }
  public static Offset<RemovePatchFB> EndRemovePatchFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemovePatchFB>(o);
  }
};


}
