// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RequestAppendEntriesFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestAppendEntriesFB GetRootAsRequestAppendEntriesFB(ByteBuffer _bb) { return GetRootAsRequestAppendEntriesFB(_bb, new RequestAppendEntriesFB()); }
  public static RequestAppendEntriesFB GetRootAsRequestAppendEntriesFB(ByteBuffer _bb, RequestAppendEntriesFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestAppendEntriesFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string NodeId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNodeIdBytes() { return __p.__vector_as_arraysegment(4); }
  public AppendEntriesFB? Request { get { int o = __p.__offset(6); return o != 0 ? (AppendEntriesFB?)(new AppendEntriesFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RequestAppendEntriesFB> CreateRequestAppendEntriesFB(FlatBufferBuilder builder,
      StringOffset NodeIdOffset = default(StringOffset),
      Offset<AppendEntriesFB> RequestOffset = default(Offset<AppendEntriesFB>)) {
    builder.StartObject(2);
    RequestAppendEntriesFB.AddRequest(builder, RequestOffset);
    RequestAppendEntriesFB.AddNodeId(builder, NodeIdOffset);
    return RequestAppendEntriesFB.EndRequestAppendEntriesFB(builder);
  }

  public static void StartRequestAppendEntriesFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddNodeId(FlatBufferBuilder builder, StringOffset NodeIdOffset) { builder.AddOffset(0, NodeIdOffset.Value, 0); }
  public static void AddRequest(FlatBufferBuilder builder, Offset<AppendEntriesFB> RequestOffset) { builder.AddOffset(1, RequestOffset.Value, 0); }
  public static Offset<RequestAppendEntriesFB> EndRequestAppendEntriesFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestAppendEntriesFB>(o);
  }
};


}
