// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class RequestAppendResponseFB : Table {
  public static RequestAppendResponseFB GetRootAsRequestAppendResponseFB(ByteBuffer _bb) { return GetRootAsRequestAppendResponseFB(_bb, new RequestAppendResponseFB()); }
  public static RequestAppendResponseFB GetRootAsRequestAppendResponseFB(ByteBuffer _bb, RequestAppendResponseFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public RequestAppendResponseFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ulong NodeId { get { int o = __offset(4); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public AppendResponseFB Response { get { return GetResponse(new AppendResponseFB()); } }
  public AppendResponseFB GetResponse(AppendResponseFB obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<RequestAppendResponseFB> CreateRequestAppendResponseFB(FlatBufferBuilder builder,
      ulong NodeId = 0,
      Offset<AppendResponseFB> ResponseOffset = default(Offset<AppendResponseFB>)) {
    builder.StartObject(2);
    RequestAppendResponseFB.AddNodeId(builder, NodeId);
    RequestAppendResponseFB.AddResponse(builder, ResponseOffset);
    return RequestAppendResponseFB.EndRequestAppendResponseFB(builder);
  }

  public static void StartRequestAppendResponseFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddNodeId(FlatBufferBuilder builder, ulong NodeId) { builder.AddUlong(0, NodeId, 0); }
  public static void AddResponse(FlatBufferBuilder builder, Offset<AppendResponseFB> ResponseOffset) { builder.AddOffset(1, ResponseOffset.Value, 0); }
  public static Offset<RequestAppendResponseFB> EndRequestAppendResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestAppendResponseFB>(o);
  }
};


}
