// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RequestSnapshotResponseFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestSnapshotResponseFB GetRootAsRequestSnapshotResponseFB(ByteBuffer _bb) { return GetRootAsRequestSnapshotResponseFB(_bb, new RequestSnapshotResponseFB()); }
  public static RequestSnapshotResponseFB GetRootAsRequestSnapshotResponseFB(ByteBuffer _bb, RequestSnapshotResponseFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestSnapshotResponseFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string NodeId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNodeIdBytes() { return __p.__vector_as_arraysegment(4); }
  public AppendResponseFB? Response { get { int o = __p.__offset(6); return o != 0 ? (AppendResponseFB?)(new AppendResponseFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RequestSnapshotResponseFB> CreateRequestSnapshotResponseFB(FlatBufferBuilder builder,
      StringOffset NodeIdOffset = default(StringOffset),
      Offset<AppendResponseFB> ResponseOffset = default(Offset<AppendResponseFB>)) {
    builder.StartObject(2);
    RequestSnapshotResponseFB.AddResponse(builder, ResponseOffset);
    RequestSnapshotResponseFB.AddNodeId(builder, NodeIdOffset);
    return RequestSnapshotResponseFB.EndRequestSnapshotResponseFB(builder);
  }

  public static void StartRequestSnapshotResponseFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddNodeId(FlatBufferBuilder builder, StringOffset NodeIdOffset) { builder.AddOffset(0, NodeIdOffset.Value, 0); }
  public static void AddResponse(FlatBufferBuilder builder, Offset<AppendResponseFB> ResponseOffset) { builder.AddOffset(1, ResponseOffset.Value, 0); }
  public static Offset<RequestSnapshotResponseFB> EndRequestSnapshotResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestSnapshotResponseFB>(o);
  }
};


}
