// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RequestVoteFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestVoteFB GetRootAsRequestVoteFB(ByteBuffer _bb) { return GetRootAsRequestVoteFB(_bb, new RequestVoteFB()); }
  public static RequestVoteFB GetRootAsRequestVoteFB(ByteBuffer _bb, RequestVoteFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestVoteFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string NodeId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNodeIdBytes() { return __p.__vector_as_arraysegment(4); }
  public VoteRequestFB? Request { get { int o = __p.__offset(6); return o != 0 ? (VoteRequestFB?)(new VoteRequestFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RequestVoteFB> CreateRequestVoteFB(FlatBufferBuilder builder,
      StringOffset NodeIdOffset = default(StringOffset),
      Offset<VoteRequestFB> RequestOffset = default(Offset<VoteRequestFB>)) {
    builder.StartObject(2);
    RequestVoteFB.AddRequest(builder, RequestOffset);
    RequestVoteFB.AddNodeId(builder, NodeIdOffset);
    return RequestVoteFB.EndRequestVoteFB(builder);
  }

  public static void StartRequestVoteFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddNodeId(FlatBufferBuilder builder, StringOffset NodeIdOffset) { builder.AddOffset(0, NodeIdOffset.Value, 0); }
  public static void AddRequest(FlatBufferBuilder builder, Offset<VoteRequestFB> RequestOffset) { builder.AddOffset(1, RequestOffset.Value, 0); }
  public static Offset<RequestVoteFB> EndRequestVoteFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestVoteFB>(o);
  }
};


}
