// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class RequestInstallSnapshotFB : Table {
  public static RequestInstallSnapshotFB GetRootAsRequestInstallSnapshotFB(ByteBuffer _bb) { return GetRootAsRequestInstallSnapshotFB(_bb, new RequestInstallSnapshotFB()); }
  public static RequestInstallSnapshotFB GetRootAsRequestInstallSnapshotFB(ByteBuffer _bb, RequestInstallSnapshotFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public RequestInstallSnapshotFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string NodeId { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetNodeIdBytes() { return __vector_as_arraysegment(4); }
  public InstallSnapshotFB Request { get { return GetRequest(new InstallSnapshotFB()); } }
  public InstallSnapshotFB GetRequest(InstallSnapshotFB obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<RequestInstallSnapshotFB> CreateRequestInstallSnapshotFB(FlatBufferBuilder builder,
      StringOffset NodeIdOffset = default(StringOffset),
      Offset<InstallSnapshotFB> RequestOffset = default(Offset<InstallSnapshotFB>)) {
    builder.StartObject(2);
    RequestInstallSnapshotFB.AddRequest(builder, RequestOffset);
    RequestInstallSnapshotFB.AddNodeId(builder, NodeIdOffset);
    return RequestInstallSnapshotFB.EndRequestInstallSnapshotFB(builder);
  }

  public static void StartRequestInstallSnapshotFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddNodeId(FlatBufferBuilder builder, StringOffset NodeIdOffset) { builder.AddOffset(0, NodeIdOffset.Value, 0); }
  public static void AddRequest(FlatBufferBuilder builder, Offset<InstallSnapshotFB> RequestOffset) { builder.AddOffset(1, RequestOffset.Value, 0); }
  public static Offset<RequestInstallSnapshotFB> EndRequestInstallSnapshotFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestInstallSnapshotFB>(o);
  }
};


}
