// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RequestInstallSnapshotFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestInstallSnapshotFB GetRootAsRequestInstallSnapshotFB(ByteBuffer _bb) { return GetRootAsRequestInstallSnapshotFB(_bb, new RequestInstallSnapshotFB()); }
  public static RequestInstallSnapshotFB GetRootAsRequestInstallSnapshotFB(ByteBuffer _bb, RequestInstallSnapshotFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestInstallSnapshotFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string NodeId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNodeIdBytes() { return __p.__vector_as_arraysegment(4); }
  public InstallSnapshotFB? Request { get { int o = __p.__offset(6); return o != 0 ? (InstallSnapshotFB?)(new InstallSnapshotFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RequestInstallSnapshotFB> CreateRequestInstallSnapshotFB(FlatBufferBuilder builder,
      StringOffset NodeIdOffset = default(StringOffset),
      Offset<InstallSnapshotFB> RequestOffset = default(Offset<InstallSnapshotFB>)) {
    builder.StartObject(2);
    RequestInstallSnapshotFB.AddRequest(builder, RequestOffset);
    RequestInstallSnapshotFB.AddNodeId(builder, NodeIdOffset);
    return RequestInstallSnapshotFB.EndRequestInstallSnapshotFB(builder);
  }

  public static void StartRequestInstallSnapshotFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddNodeId(FlatBufferBuilder builder, StringOffset NodeIdOffset) { builder.AddOffset(0, NodeIdOffset.Value, 0); }
  public static void AddRequest(FlatBufferBuilder builder, Offset<InstallSnapshotFB> RequestOffset) { builder.AddOffset(1, RequestOffset.Value, 0); }
  public static Offset<RequestInstallSnapshotFB> EndRequestInstallSnapshotFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestInstallSnapshotFB>(o);
  }
};


}
