// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct RequestVoteResponseFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestVoteResponseFB GetRootAsRequestVoteResponseFB(ByteBuffer _bb) { return GetRootAsRequestVoteResponseFB(_bb, new RequestVoteResponseFB()); }
  public static RequestVoteResponseFB GetRootAsRequestVoteResponseFB(ByteBuffer _bb, RequestVoteResponseFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestVoteResponseFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string NodeId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNodeIdBytes() { return __p.__vector_as_arraysegment(4); }
  public VoteResponseFB? Response { get { int o = __p.__offset(6); return o != 0 ? (VoteResponseFB?)(new VoteResponseFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RequestVoteResponseFB> CreateRequestVoteResponseFB(FlatBufferBuilder builder,
      StringOffset NodeIdOffset = default(StringOffset),
      Offset<VoteResponseFB> ResponseOffset = default(Offset<VoteResponseFB>)) {
    builder.StartObject(2);
    RequestVoteResponseFB.AddResponse(builder, ResponseOffset);
    RequestVoteResponseFB.AddNodeId(builder, NodeIdOffset);
    return RequestVoteResponseFB.EndRequestVoteResponseFB(builder);
  }

  public static void StartRequestVoteResponseFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddNodeId(FlatBufferBuilder builder, StringOffset NodeIdOffset) { builder.AddOffset(0, NodeIdOffset.Value, 0); }
  public static void AddResponse(FlatBufferBuilder builder, Offset<VoteResponseFB> ResponseOffset) { builder.AddOffset(1, ResponseOffset.Value, 0); }
  public static Offset<RequestVoteResponseFB> EndRequestVoteResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestVoteResponseFB>(o);
  }
};


}
