// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct SessionFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SessionFB GetRootAsSessionFB(ByteBuffer _bb) { return GetRootAsSessionFB(_bb, new SessionFB()); }
  public static SessionFB GetRootAsSessionFB(ByteBuffer _bb, SessionFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SessionFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
  public string UserName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUserNameBytes() { return __p.__vector_as_arraysegment(6); }
  public string IpAddress { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetIpAddressBytes() { return __p.__vector_as_arraysegment(8); }
  public string UserAgent { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUserAgentBytes() { return __p.__vector_as_arraysegment(10); }

  public static Offset<SessionFB> CreateSessionFB(FlatBufferBuilder builder,
      StringOffset IdOffset = default(StringOffset),
      StringOffset UserNameOffset = default(StringOffset),
      StringOffset IpAddressOffset = default(StringOffset),
      StringOffset UserAgentOffset = default(StringOffset)) {
    builder.StartObject(4);
    SessionFB.AddUserAgent(builder, UserAgentOffset);
    SessionFB.AddIpAddress(builder, IpAddressOffset);
    SessionFB.AddUserName(builder, UserNameOffset);
    SessionFB.AddId(builder, IdOffset);
    return SessionFB.EndSessionFB(builder);
  }

  public static void StartSessionFB(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddId(FlatBufferBuilder builder, StringOffset IdOffset) { builder.AddOffset(0, IdOffset.Value, 0); }
  public static void AddUserName(FlatBufferBuilder builder, StringOffset UserNameOffset) { builder.AddOffset(1, UserNameOffset.Value, 0); }
  public static void AddIpAddress(FlatBufferBuilder builder, StringOffset IpAddressOffset) { builder.AddOffset(2, IpAddressOffset.Value, 0); }
  public static void AddUserAgent(FlatBufferBuilder builder, StringOffset UserAgentOffset) { builder.AddOffset(3, UserAgentOffset.Value, 0); }
  public static Offset<SessionFB> EndSessionFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SessionFB>(o);
  }
};


}
