// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum SliceTypeFB : byte
{
 NONE = 0,
 StringSliceFB = 1,
 IntSliceFB = 2,
 FloatSliceFB = 3,
 DoubleSliceFB = 4,
 BoolSliceFB = 5,
 ByteSliceFB = 6,
 EnumSliceFB = 7,
 ColorSliceFB = 8,
 CompoundSliceFB = 9,
};


}
