// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class SliceFB : Table {
  public static SliceFB GetRootAsSliceFB(ByteBuffer _bb) { return GetRootAsSliceFB(_bb, new SliceFB()); }
  public static SliceFB GetRootAsSliceFB(ByteBuffer _bb, SliceFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public SliceFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public SliceTypeFB SliceType { get { int o = __offset(4); return o != 0 ? (SliceTypeFB)bb.Get(o + bb_pos) : SliceTypeFB.NONE; } }
  public TTable GetSlice<TTable>(TTable obj) where TTable : Table { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static Offset<SliceFB> CreateSliceFB(FlatBufferBuilder builder,
      SliceTypeFB Slice_type = SliceTypeFB.NONE,
      int SliceOffset = 0) {
    builder.StartObject(2);
    SliceFB.AddSlice(builder, SliceOffset);
    SliceFB.AddSliceType(builder, Slice_type);
    return SliceFB.EndSliceFB(builder);
  }

  public static void StartSliceFB(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddSliceType(FlatBufferBuilder builder, SliceTypeFB SliceType) { builder.AddByte(0, (byte)SliceType, 0); }
  public static void AddSlice(FlatBufferBuilder builder, int SliceOffset) { builder.AddOffset(1, SliceOffset, 0); }
  public static Offset<SliceFB> EndSliceFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SliceFB>(o);
  }
};


}
