// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct SnapshotFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SnapshotFB GetRootAsSnapshotFB(ByteBuffer _bb) { return GetRootAsSnapshotFB(_bb, new SnapshotFB()); }
  public static SnapshotFB GetRootAsSnapshotFB(ByteBuffer _bb, SnapshotFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SnapshotFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
  public uint Index { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Term { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint LastIndex { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint LastTerm { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public NodeFB? Nodes(int j) { int o = __p.__offset(14); return o != 0 ? (NodeFB?)(new NodeFB()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int NodesLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public StateMachineFB? Data { get { int o = __p.__offset(16); return o != 0 ? (StateMachineFB?)(new StateMachineFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<SnapshotFB> CreateSnapshotFB(FlatBufferBuilder builder,
      StringOffset IdOffset = default(StringOffset),
      uint Index = 0,
      uint Term = 0,
      uint LastIndex = 0,
      uint LastTerm = 0,
      VectorOffset NodesOffset = default(VectorOffset),
      Offset<StateMachineFB> DataOffset = default(Offset<StateMachineFB>)) {
    builder.StartObject(7);
    SnapshotFB.AddData(builder, DataOffset);
    SnapshotFB.AddNodes(builder, NodesOffset);
    SnapshotFB.AddLastTerm(builder, LastTerm);
    SnapshotFB.AddLastIndex(builder, LastIndex);
    SnapshotFB.AddTerm(builder, Term);
    SnapshotFB.AddIndex(builder, Index);
    SnapshotFB.AddId(builder, IdOffset);
    return SnapshotFB.EndSnapshotFB(builder);
  }

  public static void StartSnapshotFB(FlatBufferBuilder builder) { builder.StartObject(7); }
  public static void AddId(FlatBufferBuilder builder, StringOffset IdOffset) { builder.AddOffset(0, IdOffset.Value, 0); }
  public static void AddIndex(FlatBufferBuilder builder, uint Index) { builder.AddUint(1, Index, 0); }
  public static void AddTerm(FlatBufferBuilder builder, uint Term) { builder.AddUint(2, Term, 0); }
  public static void AddLastIndex(FlatBufferBuilder builder, uint LastIndex) { builder.AddUint(3, LastIndex, 0); }
  public static void AddLastTerm(FlatBufferBuilder builder, uint LastTerm) { builder.AddUint(4, LastTerm, 0); }
  public static void AddNodes(FlatBufferBuilder builder, VectorOffset NodesOffset) { builder.AddOffset(5, NodesOffset.Value, 0); }
  public static VectorOffset CreateNodesVector(FlatBufferBuilder builder, Offset<NodeFB>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartNodesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddData(FlatBufferBuilder builder, Offset<StateMachineFB> DataOffset) { builder.AddOffset(6, DataOffset.Value, 0); }
  public static Offset<SnapshotFB> EndSnapshotFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SnapshotFB>(o);
  }
};


}
