// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum StateMachineTypeFB : byte
{
 NONE = 0,
 AddCueFB = 1,
 UpdateCueFB = 2,
 RemoveCueFB = 3,
 AddCueListFB = 4,
 UpdateCueListFB = 5,
 RemoveCueListFB = 6,
 AddIOBoxFB = 7,
 UpdateIOBoxFB = 8,
 RemoveIOBoxFB = 9,
 AddPatchFB = 10,
 UpdatePatchFB = 11,
 RemovePatchFB = 12,
 AddNodeFB = 13,
 UpdateNodeFB = 14,
 RemoveNodeFB = 15,
 AddUserFB = 16,
 UpdateUserFB = 17,
 RemoveUserFB = 18,
 AddSessionFB = 19,
 UpdateSessionFB = 20,
 RemoveSessionFB = 21,
 LogMsgFB = 22,
 AppCommandFB = 23,
 DataSnapshotFB = 24,
};


}
