// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

public enum StringTypeFB : ushort
{
 SimpleFB = 0,
 MultiLineFB = 1,
 FileNameFB = 2,
 DirectoryFB = 3,
 UrlFB = 4,
 IPFB = 5,
};


}
