// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct UpdateNodeFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static UpdateNodeFB GetRootAsUpdateNodeFB(ByteBuffer _bb) { return GetRootAsUpdateNodeFB(_bb, new UpdateNodeFB()); }
  public static UpdateNodeFB GetRootAsUpdateNodeFB(ByteBuffer _bb, UpdateNodeFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UpdateNodeFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public NodeFB? Node { get { int o = __p.__offset(4); return o != 0 ? (NodeFB?)(new NodeFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<UpdateNodeFB> CreateUpdateNodeFB(FlatBufferBuilder builder,
      Offset<NodeFB> NodeOffset = default(Offset<NodeFB>)) {
    builder.StartObject(1);
    UpdateNodeFB.AddNode(builder, NodeOffset);
    return UpdateNodeFB.EndUpdateNodeFB(builder);
  }

  public static void StartUpdateNodeFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddNode(FlatBufferBuilder builder, Offset<NodeFB> NodeOffset) { builder.AddOffset(0, NodeOffset.Value, 0); }
  public static Offset<UpdateNodeFB> EndUpdateNodeFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdateNodeFB>(o);
  }
};


}
