// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class UpdateUserFB : Table {
  public static UpdateUserFB GetRootAsUpdateUserFB(ByteBuffer _bb) { return GetRootAsUpdateUserFB(_bb, new UpdateUserFB()); }
  public static UpdateUserFB GetRootAsUpdateUserFB(ByteBuffer _bb, UpdateUserFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public UpdateUserFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public UserFB User { get { return GetUser(new UserFB()); } }
  public UserFB GetUser(UserFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<UpdateUserFB> CreateUpdateUserFB(FlatBufferBuilder builder,
      Offset<UserFB> UserOffset = default(Offset<UserFB>)) {
    builder.StartObject(1);
    UpdateUserFB.AddUser(builder, UserOffset);
    return UpdateUserFB.EndUpdateUserFB(builder);
  }

  public static void StartUpdateUserFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUser(FlatBufferBuilder builder, Offset<UserFB> UserOffset) { builder.AddOffset(0, UserOffset.Value, 0); }
  public static Offset<UpdateUserFB> EndUpdateUserFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdateUserFB>(o);
  }
};


}
