// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class UpdateCueListFB : Table {
  public static UpdateCueListFB GetRootAsUpdateCueListFB(ByteBuffer _bb) { return GetRootAsUpdateCueListFB(_bb, new UpdateCueListFB()); }
  public static UpdateCueListFB GetRootAsUpdateCueListFB(ByteBuffer _bb, UpdateCueListFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public UpdateCueListFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public CueListFB CueList { get { return GetCueList(new CueListFB()); } }
  public CueListFB GetCueList(CueListFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<UpdateCueListFB> CreateUpdateCueListFB(FlatBufferBuilder builder,
      Offset<CueListFB> CueListOffset = default(Offset<CueListFB>)) {
    builder.StartObject(1);
    UpdateCueListFB.AddCueList(builder, CueListOffset);
    return UpdateCueListFB.EndUpdateCueListFB(builder);
  }

  public static void StartUpdateCueListFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCueList(FlatBufferBuilder builder, Offset<CueListFB> CueListOffset) { builder.AddOffset(0, CueListOffset.Value, 0); }
  public static Offset<UpdateCueListFB> EndUpdateCueListFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdateCueListFB>(o);
  }
};


}
