// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct UpdatePatchFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static UpdatePatchFB GetRootAsUpdatePatchFB(ByteBuffer _bb) { return GetRootAsUpdatePatchFB(_bb, new UpdatePatchFB()); }
  public static UpdatePatchFB GetRootAsUpdatePatchFB(ByteBuffer _bb, UpdatePatchFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UpdatePatchFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PatchFB? Patch { get { int o = __p.__offset(4); return o != 0 ? (PatchFB?)(new PatchFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<UpdatePatchFB> CreateUpdatePatchFB(FlatBufferBuilder builder,
      Offset<PatchFB> PatchOffset = default(Offset<PatchFB>)) {
    builder.StartObject(1);
    UpdatePatchFB.AddPatch(builder, PatchOffset);
    return UpdatePatchFB.EndUpdatePatchFB(builder);
  }

  public static void StartUpdatePatchFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPatch(FlatBufferBuilder builder, Offset<PatchFB> PatchOffset) { builder.AddOffset(0, PatchOffset.Value, 0); }
  public static Offset<UpdatePatchFB> EndUpdatePatchFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdatePatchFB>(o);
  }
};


}
