// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct UpdateUserFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static UpdateUserFB GetRootAsUpdateUserFB(ByteBuffer _bb) { return GetRootAsUpdateUserFB(_bb, new UpdateUserFB()); }
  public static UpdateUserFB GetRootAsUpdateUserFB(ByteBuffer _bb, UpdateUserFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UpdateUserFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public UserFB? User { get { int o = __p.__offset(4); return o != 0 ? (UserFB?)(new UserFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<UpdateUserFB> CreateUpdateUserFB(FlatBufferBuilder builder,
      Offset<UserFB> UserOffset = default(Offset<UserFB>)) {
    builder.StartObject(1);
    UpdateUserFB.AddUser(builder, UserOffset);
    return UpdateUserFB.EndUpdateUserFB(builder);
  }

  public static void StartUpdateUserFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUser(FlatBufferBuilder builder, Offset<UserFB> UserOffset) { builder.AddOffset(0, UserOffset.Value, 0); }
  public static Offset<UpdateUserFB> EndUpdateUserFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdateUserFB>(o);
  }
};


}
