// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class UpdateCueFB : Table {
  public static UpdateCueFB GetRootAsUpdateCueFB(ByteBuffer _bb) { return GetRootAsUpdateCueFB(_bb, new UpdateCueFB()); }
  public static UpdateCueFB GetRootAsUpdateCueFB(ByteBuffer _bb, UpdateCueFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public UpdateCueFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public CueFB Cue { get { return GetCue(new CueFB()); } }
  public CueFB GetCue(CueFB obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<UpdateCueFB> CreateUpdateCueFB(FlatBufferBuilder builder,
      Offset<CueFB> CueOffset = default(Offset<CueFB>)) {
    builder.StartObject(1);
    UpdateCueFB.AddCue(builder, CueOffset);
    return UpdateCueFB.EndUpdateCueFB(builder);
  }

  public static void StartUpdateCueFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCue(FlatBufferBuilder builder, Offset<CueFB> CueOffset) { builder.AddOffset(0, CueOffset.Value, 0); }
  public static Offset<UpdateCueFB> EndUpdateCueFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdateCueFB>(o);
  }
};


}
