// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct UpdateSessionFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static UpdateSessionFB GetRootAsUpdateSessionFB(ByteBuffer _bb) { return GetRootAsUpdateSessionFB(_bb, new UpdateSessionFB()); }
  public static UpdateSessionFB GetRootAsUpdateSessionFB(ByteBuffer _bb, UpdateSessionFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UpdateSessionFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SessionFB? Session { get { int o = __p.__offset(4); return o != 0 ? (SessionFB?)(new SessionFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<UpdateSessionFB> CreateUpdateSessionFB(FlatBufferBuilder builder,
      Offset<SessionFB> SessionOffset = default(Offset<SessionFB>)) {
    builder.StartObject(1);
    UpdateSessionFB.AddSession(builder, SessionOffset);
    return UpdateSessionFB.EndUpdateSessionFB(builder);
  }

  public static void StartUpdateSessionFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSession(FlatBufferBuilder builder, Offset<SessionFB> SessionOffset) { builder.AddOffset(0, SessionOffset.Value, 0); }
  public static Offset<UpdateSessionFB> EndUpdateSessionFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdateSessionFB>(o);
  }
};


}
