// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct UpdateIOBoxFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static UpdateIOBoxFB GetRootAsUpdateIOBoxFB(ByteBuffer _bb) { return GetRootAsUpdateIOBoxFB(_bb, new UpdateIOBoxFB()); }
  public static UpdateIOBoxFB GetRootAsUpdateIOBoxFB(ByteBuffer _bb, UpdateIOBoxFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UpdateIOBoxFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public IOBoxFB? IOBox { get { int o = __p.__offset(4); return o != 0 ? (IOBoxFB?)(new IOBoxFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<UpdateIOBoxFB> CreateUpdateIOBoxFB(FlatBufferBuilder builder,
      Offset<IOBoxFB> IOBoxOffset = default(Offset<IOBoxFB>)) {
    builder.StartObject(1);
    UpdateIOBoxFB.AddIOBox(builder, IOBoxOffset);
    return UpdateIOBoxFB.EndUpdateIOBoxFB(builder);
  }

  public static void StartUpdateIOBoxFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddIOBox(FlatBufferBuilder builder, Offset<IOBoxFB> IOBoxOffset) { builder.AddOffset(0, IOBoxOffset.Value, 0); }
  public static Offset<UpdateIOBoxFB> EndUpdateIOBoxFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UpdateIOBoxFB>(o);
  }
};


}
