// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class VoteRequestFB : Table {
  public static VoteRequestFB GetRootAsVoteRequestFB(ByteBuffer _bb) { return GetRootAsVoteRequestFB(_bb, new VoteRequestFB()); }
  public static VoteRequestFB GetRootAsVoteRequestFB(ByteBuffer _bb, VoteRequestFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public VoteRequestFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ulong Term { get { int o = __offset(4); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public NodeFB Candidate { get { return GetCandidate(new NodeFB()); } }
  public NodeFB GetCandidate(NodeFB obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public ulong LastLogIndex { get { int o = __offset(8); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public ulong LastLogTerm { get { int o = __offset(10); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }

  public static Offset<VoteRequestFB> CreateVoteRequestFB(FlatBufferBuilder builder,
      ulong Term = 0,
      Offset<NodeFB> CandidateOffset = default(Offset<NodeFB>),
      ulong LastLogIndex = 0,
      ulong LastLogTerm = 0) {
    builder.StartObject(4);
    VoteRequestFB.AddLastLogTerm(builder, LastLogTerm);
    VoteRequestFB.AddLastLogIndex(builder, LastLogIndex);
    VoteRequestFB.AddTerm(builder, Term);
    VoteRequestFB.AddCandidate(builder, CandidateOffset);
    return VoteRequestFB.EndVoteRequestFB(builder);
  }

  public static void StartVoteRequestFB(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddTerm(FlatBufferBuilder builder, ulong Term) { builder.AddUlong(0, Term, 0); }
  public static void AddCandidate(FlatBufferBuilder builder, Offset<NodeFB> CandidateOffset) { builder.AddOffset(1, CandidateOffset.Value, 0); }
  public static void AddLastLogIndex(FlatBufferBuilder builder, ulong LastLogIndex) { builder.AddUlong(2, LastLogIndex, 0); }
  public static void AddLastLogTerm(FlatBufferBuilder builder, ulong LastLogTerm) { builder.AddUlong(3, LastLogTerm, 0); }
  public static Offset<VoteRequestFB> EndVoteRequestFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<VoteRequestFB>(o);
  }
};


}
