// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class VoteResponseFB : Table {
  public static VoteResponseFB GetRootAsVoteResponseFB(ByteBuffer _bb) { return GetRootAsVoteResponseFB(_bb, new VoteResponseFB()); }
  public static VoteResponseFB GetRootAsVoteResponseFB(ByteBuffer _bb, VoteResponseFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public VoteResponseFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public ulong Term { get { int o = __offset(4); return o != 0 ? bb.GetUlong(o + bb_pos) : (ulong)0; } }
  public bool Granted { get { int o = __offset(6); return o != 0 ? 0!=bb.Get(o + bb_pos) : (bool)false; } }
  public RaftErrorFB Reason { get { return GetReason(new RaftErrorFB()); } }
  public RaftErrorFB GetReason(RaftErrorFB obj) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static Offset<VoteResponseFB> CreateVoteResponseFB(FlatBufferBuilder builder,
      ulong Term = 0,
      bool Granted = false,
      Offset<RaftErrorFB> ReasonOffset = default(Offset<RaftErrorFB>)) {
    builder.StartObject(3);
    VoteResponseFB.AddTerm(builder, Term);
    VoteResponseFB.AddReason(builder, ReasonOffset);
    VoteResponseFB.AddGranted(builder, Granted);
    return VoteResponseFB.EndVoteResponseFB(builder);
  }

  public static void StartVoteResponseFB(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddTerm(FlatBufferBuilder builder, ulong Term) { builder.AddUlong(0, Term, 0); }
  public static void AddGranted(FlatBufferBuilder builder, bool Granted) { builder.AddBool(1, Granted, false); }
  public static void AddReason(FlatBufferBuilder builder, Offset<RaftErrorFB> ReasonOffset) { builder.AddOffset(2, ReasonOffset.Value, 0); }
  public static Offset<VoteResponseFB> EndVoteResponseFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<VoteResponseFB>(o);
  }
};


}
