// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public struct WelcomeFB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static WelcomeFB GetRootAsWelcomeFB(ByteBuffer _bb) { return GetRootAsWelcomeFB(_bb, new WelcomeFB()); }
  public static WelcomeFB GetRootAsWelcomeFB(ByteBuffer _bb, WelcomeFB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public WelcomeFB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public NodeFB? Node { get { int o = __p.__offset(4); return o != 0 ? (NodeFB?)(new NodeFB()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<WelcomeFB> CreateWelcomeFB(FlatBufferBuilder builder,
      Offset<NodeFB> NodeOffset = default(Offset<NodeFB>)) {
    builder.StartObject(1);
    WelcomeFB.AddNode(builder, NodeOffset);
    return WelcomeFB.EndWelcomeFB(builder);
  }

  public static void StartWelcomeFB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddNode(FlatBufferBuilder builder, Offset<NodeFB> NodeOffset) { builder.AddOffset(0, NodeOffset.Value, 0); }
  public static Offset<WelcomeFB> EndWelcomeFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<WelcomeFB>(o);
  }
};


}
