// automatically generated by the FlatBuffers compiler, do not modify

namespace Iris.Serialization.Raft
{

using System;
using FlatBuffers;

public sealed class WelcomeFB : Table {
  public static WelcomeFB GetRootAsWelcomeFB(ByteBuffer _bb) { return GetRootAsWelcomeFB(_bb, new WelcomeFB()); }
  public static WelcomeFB GetRootAsWelcomeFB(ByteBuffer _bb, WelcomeFB obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public WelcomeFB __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void StartWelcomeFB(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<WelcomeFB> EndWelcomeFB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<WelcomeFB>(o);
  }
};


}
