#load @"System.Buffers.fsx" 
#load @"System.IO.Compression.fsx" 
#load @"System.IO.FileSystem.fsx" 
#load @"System.IO.FileSystem.Primitives.fsx" 
#r "../../../../packages/test/System.IO.Compression.ZipFile/lib/netstandard1.3/System.IO.Compression.ZipFile.dll" 