#r "../../../../packages/test/Mono.Cecil/lib/net35/Mono.Cecil.dll" 
#r "../../../../packages/test/Argu/lib/net35/Argu.dll" 
#r "../../../../packages/test/Mono.Cecil/lib/net35/Mono.Cecil.Rocks.dll" 
#r "../../../../packages/test/Mono.Cecil/lib/net35/Mono.Cecil.Pdb.dll" 
#r "../../../../packages/test/Mono.Cecil/lib/net35/Mono.Cecil.Mdb.dll" 