#load @"System.Collections.fsx" 
#load @"System.Diagnostics.Tracing.fsx" 
#load @"System.Reflection.fsx" 
#load @"System.Runtime.fsx" 
#load @"System.Threading.fsx" 
#r "../../../../packages/test/System.Diagnostics.DiagnosticSource/lib/net46/System.Diagnostics.DiagnosticSource.dll" 